### PR TITLE
Add assets for 'SHIBAX-7baf9d'

### PR DESCRIPTION
**Pull request by ShibaversX**
[info.json](https://github.com/multiversx/mx-assets/files/15143107/info.json)
logo
logo

### CODE REVIEW

**Review by ShibaversX — COMMENTED** [review]
{
  "website": "https://linktr.ee/shibaxmvx",
  "description": "ShibaX: 10,000 unique NFTs on MultiversX, offering exclusive benefits with XSHIB token.",
  "social": {
    "email": "shibaverx@gmail.com",
    "telegram": "https://t.me/+mv84eZWSB-MzMGY0",
    "twitter": "https://twitter.com/ShibaXSHIB"
  },
  "status": "active"
}

**Review by ShibaversX — COMMENTED** [review]
{
  "website": "https://linktr.ee/shibaxmvx",
  "description": "ShibaX: 10,000 unique NFTs on MultiversX, offering exclusive benefits with XSHIB token.",
  "social": {
    "email": "shibaverx@gmail.com",
    "telegram": "https://t.me/+mv84eZWSB-MzMGY0",
    "twitter": "https://twitter.com/ShibaXSHIB"
  },
  "status": "active"
}
logo
logo

**Comment by paulmultiversx** [comment]
Hi, @ShibaversX 

This PR is invalid. 
Your PR must have exactly 3 files and all the files need to be added in the Tokens directory:

info.json (https://docs.multiversx.com/tokens/esdt-tokens) 
logo.svg (must be in a square format) 
logo.png (must have a resolution of 200x200 pixels)
max logo size 100KB

Please use the Assets dApp to create a new PR: https://assets.multiversx.com/

Thanks.

**Comment by ShibaversX** [comment]
Should we use https://assets.multiversx.com/ as well to get the ShibaX collection verified?

**Comment by paulmultiversx** [comment]
Affirmative

**Pull request closed without merging**
