### PR TITLE
Add assets for CUMBX-762eec and CUMB-8b7006

### PR DESCRIPTION
**Pull request by psyrode**

### CODE REVIEW

**Comment by psyrode** [comment]
Sorry, this is the svg file correct!
logo

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @psyrode.

Please review the issues above Invalid dimensions for PNG! ( 834 x 834 ) and follow the guidelines to maximize the chances of passing through the filters, which are in place to create a healthy and sustainable token ecosystem: https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Thanks.

**Comment by psyrode** [comment]
hi @paulmultiversx , thank you very much for your feedback! i uploaded wrong file .png, now i fixed with the 200x200 logo file!

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hey, @psyrode.

It seems you have an issue with your uploaded json, please fix it so we can continue with the verifications: 
(Error: Failed to validate all JSON files.)

**Comment by psyrode** [comment]
Thanks @paulmultiversx ! Jsons fixed!

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
