### PR TITLE
Add assets for 'EDIA-60b86f'

### PR DESCRIPTION
**Pull request by Wavenodevalidat**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by Wavenodevalidat** [comment]
it's done

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Wavenodevalidat 

Your logo is too large! (176 KB)
Max dimension is 100KB. 

Please provide a signature for the latest commit sha: `16b0ec3c9bb21896c1abc9c83b0e836064c684b1` which must be signed with the owner wallet address: 
`erd1aw5u9z9r6zgke3hslx68mzxngfk3ntru8qc6sca455jkmy9smt2qxlurwz`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by Wavenodevalidat** [comment]
{
  "address": "erd1aw5u9z9r6zgke3hslx68mzxngfk3ntru8qc6sca455jkmy9smt2qxlurwz",
  "message": "0x30663831353134373436616164653037343230643235336164663134313565663162303238383831",
  "signature": "0x27e62646cb5ae7c6cfaa0e0172b5563439dd4d859cca343b171a1fd15af95d5a2d064009cf3ed37a29ac424b63ca495ecfd2de549c6f11a00e293c4f4c9c6c0e",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by Wavenodevalidat** [comment]
{
  "address": "erd1aw5u9z9r6zgke3hslx68mzxngfk3ntru8qc6sca455jkmy9smt2qxlurwz",
  "message": "0x3136623065633363396262323138393663316162633963383362306538333630363463363834623120",
  "signature": "0x173e6815c7218a211075f491128bb7658d6ab5f443a9a4750960331d4abb7ded6ec26746a3a34ab609cf191680154dda12c481a17788fe6ab8c93989badf0702",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Wavenodevalidat 

You have an invalid dimensions for the PNG! ( 400 x 400 )

The resolution should be 200x200.

Please fix it so we can proceed with the merging of this PR.

Thanks

**Comment by Wavenodevalidat** [comment]
{
  "address": "erd1aw5u9z9r6zgke3hslx68mzxngfk3ntru8qc6sca455jkmy9smt2qxlurwz",
  "message": "0x38666230613039636634623762373366353338613137383436366362643739613933336636353134",
  "signature": "0xf1c54aa4fb91de9235538a3f66fd88c1afd7e5b8930388456ab9f37b2ce766bb8a444fc7873ca7f31ccb93510c2caf5d862d776cedc38f659cb3fd9235820001",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Wavenodevalidat

It seems there are still issues with your PR which is why it does not pass the Github checks.
I recommend you create it using our Assets dApp and it should be valid: https://assets.multiversx.com/

Prepare the relevant token files:

 info.json (https://docs.multiversx.com/tokens/esdt-tokens)
 logo.svg (must be in a square format)
 logo.png (must have a resolution of 200x200 pixels) 
 max logo size: 100KB

Once properly created, feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Pull request closed without merging**
