### PR TITLE
Add assets for OAGMYSTERY-f98294

### PR DESCRIPTION
**Pull request by allecks93**

### CODE REVIEW

**Comment by allecks93** [comment]
{
  "address": "erd17he6kcepvs2dk3u66qq9kqj2wp7u9vkxnf93u5fn6me62edd9aqqwak0ag",
  "message": "0x31346535353036303633626565383665353834623136636161646663613035333335393936633062",
  "signature": "0x2791f1bc3b174120fbe97aaace3c6d786532aee61edad86f02511eb5198cdd3ca9020e30a37599302911aae71e7f87e406a3bebf9630b62dfd49deac3c205405",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by paulmultiversx** [comment]
Hey, @allecks93 

Your logo is transparent. Are you sure this is the way you want it?

**Comment by allecks93** [comment]
Uploaded new logo.png & logo.svg 

Thank you Paul!

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hey, @allecks93 

It seems your logo is too large (344KB). Max size should be 100KB.

Also, please provide a signature for the latest commit sha: `fb5211d5d97474f1b0da7a6b2a23f834b8caea54` which must be signed with the owner wallet address: 
`erd1qqqqqqqqqqqqqpgqg9fa0dmpn8fu3fnleeqn5zt8rl8mdqjkys5s2gtas7`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by allecks93** [comment]
Sorry for my oversight.
Uploaded new .svg and signed last commit sha:

{
  "address": "erd17he6kcepvs2dk3u66qq9kqj2wp7u9vkxnf93u5fn6me62edd9aqqwak0ag",
  "message": "0x37376139373339643231353761326236323732613565663633323138323831653035313761333864",
  "signature": "0x99a8c55341baeefaf086fa3536d87329b19cf4d972821de4e6121c260b304bae3bc687a2698200e9ed873cea86cb2b0e690706edb04f09ae7fe94b0679579d0c",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
