### PR TITLE
Add assets for contract erd1qqqqqqqqqqqqqpgqpt8qksprd987dyy3fqzxuqr9yde7el3q8chqnvyc93

### PR DESCRIPTION
**Pull request by mantacalin**

### CODE REVIEW

**Comment by mantacalin** [comment]
I would like to add branding assets for token AIRO-8ac04b

**Comment by mantacalin** [comment]
[info.json](https://github.com/multiversx/mx-assets/files/13449962/info.json)
logo
logo

**Comment by paulmultiversx** [comment]
Hey, @mantacalin.

Your PR has multiple issues, please redo it, but make sure you use the dedicated Assets dApp this time: https://assets.multiversx.com/

Please follow the guidelines to maximize the chances of passing through the filters, which are in place to create a healthy and sustainable token ecosystem: https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Thanks.

**Comment by mantacalin** [comment]
This is exactly the method I have used. I opened the Pull Request through the app with the address that is the owner of the AIRO SC. What can I do?Sent from my iPhoneOn 24 Nov 2023, at 18:07, Paul | MultiversX ***@***.***> wrote:﻿
Hey, @mantacalin.
Your PR has multiple issues, please redo it, but make sure you use the dedicated Assets dApp this time: https://assets.multiversx.com/
Please follow the guidelines to maximize the chances of passing through the filters, which are in place to create a healthy and sustainable token ecosystem: https://multiversx.com/blog/branding-esdt-tokens-nft-collections/
Thanks.

**Pull request closed without merging**
