### PR TITLE
Add assets for 'FEET-096185'

### PR DESCRIPTION
**Pull request by FeetToken**

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @FeetToken 

Your logo.svg is invalid. Please fix it before we can continue with the merging of this PR.

Please provide a signature for the latest commit sha: `190685933a7bbb34ea339fab7b5819f118243761` which must be signed with the owner wallet address: 
`erd1gtyx29km7m0j4dy90q5gdkynlf9cmn9jhgyuy64dc9r2ln8tj9aq8h2js4`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by FeetToken** [comment]
logo.svg is valid now ? And i singed

**Comment by paulmultiversx** [comment]
@FeetToken you need to actually paste the signature here in a new comment. Thanks.

**Comment by FeetToken** [comment]
c742d7d9e939533796149746f4d2c4c0ed7b64bd638ceb3996b39a0327e057b5ee24e85564b40235496661c5233a586c24c949509e066dee9be9b8d2c5afb300

**Review by paulmultiversx — APPROVED** [review]

**Comment by FeetToken** [comment]
Hi @paulmultiversx.
Is that possible to delete the token ?

**Comment by paulmultiversx** [comment]
Hi, @FeetToken 

You can't delete a token created on the blockchain but you can delete the branding from Github or update it. 

Here's a document containing all specs you need to know about creating and managing an ESDT: 
https://docs.multiversx.com/tokens/overview

**Pull request merged**
