### PR TITLE
Add assets for 'CryptGain'

### PR DESCRIPTION
**Pull request by newtmex**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @newtmex 

Please provide a signature for the latest commit sha: `e2e5a589b21d59b221c90bb090862652eb9ead17` which must be signed with the owner wallet address: 
`erd16myes42p5t6xnxkxw8jghg8sypuammz9fc44g4f2u43dj2hd0fusp9286j`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by newtmex** [comment]
@paulmultiversx here's the signature

```json
{
  "address": "erd1572z9p2j2dvluchjn070pdj5tfmgh9qu69yxf2uzaplaq45qfykqxx0utw",
  "message": "0x65326535613538396232316435396232323163393062623039303836323635326562396561643137",
  "signature": "0x6a5eb88d7f69346a6be1e135d8c4cec634b3f35a666abc859c42600a00ba98f25d882d1ae0a03c68db3e75b9f68d3b65dd5467084305e7af2608adf542f0e909",
  "version": 1,
  "signer": "ErdJS"
}
```

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hey, @newtmex. Your signature is invalid.

Please provide a signature for the latest commit sha: `8db2c99d81371debbfa3b975e3e3faeac00154a6` which must be signed with the owner wallet address: 
`erd16myes42p5t6xnxkxw8jghg8sypuammz9fc44g4f2u43dj2hd0fusp9286j`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by newtmex** [comment]
@paulmultiversx 
```json
{
  "address": "erd16myes42p5t6xnxkxw8jghg8sypuammz9fc44g4f2u43dj2hd0fusp9286j",
  "message": "0x38646232633939643831333731646562626661336239373565336533666165616330303135346136",
  "signature": "0x2cb7c5f319f51748e1e48782a3ba847e199ba3d1e52db27751c4275c0cac32ac0a2803410ba81cbf507244a5a2e62e776adaa47da3c22fe8b9aa3d96c9965e00",
  "version": 1,
  "signer": "ErdJS"
}
```

**Comment by newtmex** [comment]
0xfe2b243ec2c37a36a3c4732fb92fc84efc06211e9340657f9b42d470682b393bfd6062e3399de828f209c233f087ffcd983efccc716a4034a31efbb4cd40c60b

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
