### PR TITLE
Add assets for 'WAGMI-3f803d'

### PR DESCRIPTION
**Pull request by wagmifoundation**

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hi, @wagmifoundation.

Please work on your website, grow your community to reach the minimum requirements in terms of followers, work on your holders number until you reach a minimum 1000 holders & transactions then create a new PR following the guidelines to maximize the chances of passing through the filters, which are in place to create a healthy and sustainable token ecosystem: https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Thanks.

**Comment by wagmifoundation** [comment]
As the rules for branding have now changed? Can we be whitelisted at this point? Thanks

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @wagmifoundation 

That is correct, you can brand your token now without any token holders requirements.

Please provide a signature for the latest commit sha: `94741737dd13152c91623f099bab6dc31c0bb1b9` which must be signed with the owner wallet address: 
`erd1lkj6ceyg5rmc880j49urmfh3dkdg2yv0kkfuw69z3h02e25f0t0q2elng5`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

**Comment by wagmifoundation** [comment]
Thank you Paul, I want to make sure I'm doing this correctly

I went to the utils page and filled out the information as follows. But I
don't think that did anything. Can you assist?

[image: Screenshot 2024-03-20 at 10.02.03 AM.png][image: Screenshot
2024-03-20 at 10.01.55 AM.png]

**Comment by paulmultiversx** [comment]
Hey, @wagmifoundation 

You just need to paste the signature here in a new comment for the latest commit sha: `94741737dd13152c91623f099bab6dc31c0bb1b9` which must be signed with the owner wallet address: 
`erd1lkj6ceyg5rmc880j49urmfh3dkdg2yv0kkfuw69z3h02e25f0t0q2elng5`

Thanks.

**Pull request closed without merging**
