### PR TITLE
Add assets for 'greenplanetedc'

### PR DESCRIPTION
**Pull request by GreenPlanetEDC**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hi, @GreenPlanetEDC.

Please provide a signature for the latest commit sha: `399c0ce06a570ba519c0eaba19735b256b190244` which must be signed with the owner wallet address: 
`erd1avgazjlz9g2jl0jelpzq2xvzmrzxa5eexwrpphz2k6nfhk8xtmvqgrvwar`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks.

**Comment by GreenPlanetEDC** [comment]
Hi Paul,
Please check the signature sent from our wallet as requested.
Thanks,Maria
    On Monday, 4 March 2024 at 12:24:57 GMT, Paul | MultiversX ***@***.***> wrote:  
 
 


@paulmultiversx requested changes on this pull request.

Hi, @GreenPlanetEDC.

Please provide a signature for the latest commit sha: 399c0ce06a570ba519c0eaba19735b256b190244 which must be signed with the owner wallet address:
erd1avgazjlz9g2jl0jelpzq2xvzmrzxa5eexwrpphz2k6nfhk8xtmvqgrvwar

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks.

**Comment by paulmultiversx** [comment]
Hi, @GreenPlanetEDC.

Please paste the signature in a new comment here.

Thanks.

**Comment by GreenPlanetEDC** [comment]
Hi,
Please see below the signature.{"address":"erd1avgazjlz9g2jl0jelpzq2xvzmrzxa5eexwrpphz2k6nfhk8xtmvqgrvwar","message":"0x33393963306365303661353730626135313963306561626131393733356232353662313930323434","signature":"0xb6cc9726b334a25760db91b68b97fbaf083e465ea5601840aca4746a8efa00b32613a38a06915dd131c0272a04643d93590f5634f5164cda99734d9513e19f03","version":1,"signer":"ErdJS"}

Best regards,Maria


    On Monday, 11 March 2024 at 08:41:44 GMT, Paul | MultiversX ***@***.***> wrote:  
 
 


Hi, @GreenPlanetEDC.
Please paste the signature in a new comment here.
Thanks.

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
