### PR TITLE
Update AshSwap logo

### PR DESCRIPTION
**Pull request by phanletrunghieu**
Commit hash: 1dd9bab0afbf22a5bacdfe7be292fd94b3469083
Address: erd15xh20eyfdaqurvkqy99uf56w0qmcwy8jv0twmguuxnn6ypax4fvsvpgp7n
Signature: 0x0572e3af3b20ff98963b627482532cfc476db546813142aff7df74645515d10cda6493d3c52d7169f2feb0c2c84dd4bf71a25ddbfa9e4080aff6236d0dafb807

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hi, @phanletrunghieu 

Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Comment by phanletrunghieu** [comment]
Thank @paulmultiversx . Updated

**Comment by paulmultiversx** [comment]
@phanletrunghieu the branch is out of date again. 

If you create the PR using the Assets dApp this won't happen: https://assets.multiversx.com/

**Comment by phanletrunghieu** [comment]
Hi @paulmultiversx . I updated the PR. I can't find the way to update only the icon at https://assets.multiversx.com.

**Comment by paulmultiversx** [comment]
Hi, @phanletrunghieu 

@phanletrunghieu the branch is out of date again.

Please tag me once it's done. Thanks

**Comment by phanletrunghieu** [comment]
Thank @paulmultiversx . I updated again. 🤗

**Pull request merged**
