### PR TITLE
Add assets for 'SPONGE-9605e6'

### PR DESCRIPTION
**Pull request by SpongeversX**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @SpongeversX 

Please provide a signature for the latest commit sha: `c6cc2a32cfa1bf3a8181112ff651f5c95c9440f9` which must be signed with the owner wallet address: 
`erd1se2lgw7e30u7h54028ktm0vkttr5c5wpwxm0kzvx8aeunwmp6ltqkhc295`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by SpongeversX** [comment]
[image: image.png]

Bonjour monsieur, j'ai essayé de signer plusieurs fois, mais rien ne se
produit, j'ai juste eu ceci :

{
"address": "erd1se2lgw7e30u7h54028ktm0vkttr5c5wpwxm0kzvx8aeunwmp6ltqkhc295",
"message":
"0x32383033313166373432366636366232643332356235346130313235646264386239376561313965",
"signature":
"0xb0473264babec54038ef9d27184beda69440afea1d69d01557001eae7bc60009f41a0964ddc3146785407702f3e231e1467c2dab21d8341078655524ea284708",
"version": 1,
"signer": "ErdJS"
}

Et quand je vérifie la signature, ça me dit invalide.

Est-ce que vous sauriez m'éclairer s'il vous plaît, j'ai du mal, je suis
une éponge

**Comment by SpongeversX** [comment]
Ah, je crois que c'est bon ? Autant pour moi je l'utilisais mal !

[image: image.png]

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @SpongeversX 

Please provide a signature for the latest commit sha: `0c97be8c55c60683ef530729c05da518b82da1ae` which must be signed with the owner wallet address: 
`erd1se2lgw7e30u7h54028ktm0vkttr5c5wpwxm0kzvx8aeunwmp6ltqkhc295`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by SpongeversX** [comment]
Hello @paulmultiversx 

Could you please check if everything is good

We're ready to absorb it all.

Best regards, 

The sponge.

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @SpongeversX 

Please understand this PR will not be merged if you do not paste the required signature in a comment to this PR. 

Please provide a signature for the latest commit sha: `aaee6dff2ce120ff204850fe3dc4952747120e75` which must be signed with the owner wallet address: 
`erd1se2lgw7e30u7h54028ktm0vkttr5c5wpwxm0kzvx8aeunwmp6ltqkhc295`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by SpongeversX** [comment]
Done sir, 

{
  "address": "erd1se2lgw7e30u7h54028ktm0vkttr5c5wpwxm0kzvx8aeunwmp6ltqkhc295",
  "message": "0x61616565366466663263653132306666323034383530666533646334393532373437313230653735",
  "signature": "0x90cc25b844fb782aaaea2ae3e0272ab729a07c2b1627beec709f02108c8283b29c219f7a773cde0f5de21f6d554a4a5b950e68341ca0d2be743cc3ac1fcdb700",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by SpongeversX** [comment]
@paulmultiversx 

Thanks for u time

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
