### PR TITLE
Add assets for 'BWIF-753394'

### PR DESCRIPTION
**Pull request by boberwif**

### CODE REVIEW

**Comment by boberwif** [comment]
{
  "address": "erd1xmetjsv4r4s5ln87c5469fcnwumvyeq82jan4ay6hjmynngtltws93ezy5",
  "message": "0x61313433613365616565396635306536663335313065616536393263363161366330336532333932",
  "signature": "0x13cbfd22d9f36b04471f239e44193852ba92d0d5499d3342db18dd78c73769c95963c0caa86a3548506dd6d456d72cec32900d2df4a881d8de593535be5de000",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by boberwif** [comment]
Hi @paulmultiversx, could you please take a look at our PR? :D
Thank you.

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @boberwif 

Your logo is too large: _File tokens/BWIF-753394/logo.svg is too large! (432 KB)_

Please upload it properly so we can proceed.

Thanks

**Comment by paulmultiversx** [comment]
@boberwif 

logo.svg (must be in a square format)

logo.png (must have a resolution of 200x200 pixels)  

max size 100KB

**Comment by boberwif** [comment]
@paulmultiversx 

logo.svg is square format.

We have re-uploaded the logo.png.

**Comment by boberwif** [comment]
Could you check if it's alright? @paulmultiversx We are looking to launch today.

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
