### PR TITLE
Add assets for 'FRID-1d2e39'

### PR DESCRIPTION
**Pull request by 123Razvan**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @123Razvan 

Please provide a signature for the latest commit sha: `a3ddd984c2194b0679b8421a3566fa4ce7774b95` which must be signed with the owner wallet address: 
`erd1dzk4j7l7le6m5csgnwk8z8ulkd63a0fnak3wdpryunpr2wq24nlshapvpv`


Feel free to use the Sign Message feature from the Utils dApp and paste the signature here in a comment: https://utils.multiversx.com/

Step-by-step guide:

Step 1: Copy latest commit sha
Step 2: Open: https://utils.multiversx.com/
Step 3: Log in with your owner address wallet
Step 4: Click the 'Sign Message' feature
Step 5: Paste the commit sha in the first column and hit sign
Step 6: Copy-paste the provided output signature here in a new comment

Thanks.

**Comment by 123Razvan** [comment]
{
  "address": "erd1dzk4j7l7le6m5csgnwk8z8ulkd63a0fnak3wdpryunpr2wq24nlshapvpv",
  "message": "0x2061336464643938346332313934623036373962383432316133353636666134636537373734623935",
  "signature": "0x16a9256cd76193032de7ca87d2052179bd00febbb44e4d1808c56ae3a6a5158997967058b6385660419fe213cee9c156766072a9606d7bf3652330e84777ab09",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by 123Razvan** [comment]
Could you please push and commit again, was not signed

**Comment by paulmultiversx** [comment]
Hi, @123Razvan 

It appears the signature is not valid. 

Please sign the latest commit sha: `aa97512227260279dfb5b9454ff3cd3cc6810c0e` 

using the owner wallet address: 
`erd1dzk4j7l7le6m5csgnwk8z8ulkd63a0fnak3wdpryunpr2wq24nlshapvpv`

Thanks.

**Comment by 123Razvan** [comment]
{
  "address": "erd1dzk4j7l7le6m5csgnwk8z8ulkd63a0fnak3wdpryunpr2wq24nlshapvpv",
  "message": "0x61613937353132323237323630323739646662356239343534666633636433636336383130633065",
  "signature": "0xfb56658f4f65e60334b8c4ea019aed48d08e75c01cfb5470cac692631333f324115d9c616f4dcadfebbbc5075c54152585e580801416fd48234dd27ed3236805",
  "version": 1,
  "signer": "ErdJS"
}

**Pull request merged**
