### PR TITLE
Add assets for 'MOJO-98e7ed'

### PR DESCRIPTION
**Pull request by los7701**

### CODE REVIEW

**Comment by los7701** [comment]
9c9e916963be371fd838defd34f5a99bbb9f0cc30ef75708cf521c046744ed7913b6f301d2d4cbeb0090e08a95f607c2fcd2def7b2e6198da96e797538d99108

**Review by los7701 — COMMENTED** [review]
Final changes

**Comment by los7701** [comment]
a7094f421a03a6f2f4ac67949043dce76717e4cf9445111d3e00fc3b0ad3cbe91ef20ba710ab38bd207c4e500129022086bcb3d35cc88878c2b607cfead7a707

**Comment by paulmultiversx** [comment]
Hey, @los7701. Your PR is invalid.

Your PR must have 3 files and all the files need to be added in the Tokens directory:

info.json (https://docs.multiversx.com/tokens/esdt-tokens) 
logo.svg (must be in a square format) 
logo.png (must have a resolution of 200x200 pixels) 
max logo size 100KB

Please use the Assets dApp to create a new PR: https://assets.multiversx.com/

Also, don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Pull request closed without merging**
