### PR TITLE
Add assets for 'CRHEROES-9edff2'

### PR DESCRIPTION
**Pull request by pErsten**
{
  "address": "erd1twt77wkq9cjfla6rxsmynqhznh272cfgvp846xmtj0u97see25xsmgxl4s",
  "message": "0x65653362383964353961323837303037656439313230656635616264653762613433663137653366",
  "signature": "0xb63e4312bbd6f4748ee3883fb88d49d825d5237886b57949f3ab4a903afd73c5954db4ea0588eb2fd45851557061becab01e420befd51be10ba4543a74aa760b",
  "version": 1,
  "signer": "ErdJS"
}

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @pErsten 

You have an invalid dimension for your logo.

logo.png must have a resolution of 200x200 pixels
max logo size 100KB

Also, the signature provided is not signed with the owner wallet address.

You need to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — APPROVED** [review]

**Comment by cfaur09** [comment]
0xb63e4312bbd6f4748ee3883fb88d49d825d5237886b57949f3ab4a903afd73c5954db4ea0588eb2fd45851557061becab01e420befd51be10ba4543a74aa760b

**Comment by pErsten** [comment]
{
  “address”: “erd102975u07wnv0t8pl389l6dag2r9ca8ql2dsjvgc8jp59a39ycd4q4dsfdw”,
  “message”: “0x33396432393338303332316133316163353266316164316630666538326632333138386466326665",
  “signature”: “0x68f224593ebb910602ed95c62067ed42dfaf43efad1716934960268661135d736aa1332b959bc8a36ddb7ec140cebf9fee9e354078082310423fc1dde5207609",
  “version”: 1,
  “signer”: “ErdJS”
}

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @pErsten 

Your logo has 300KB. Max logo size is 100KB as already stated in the previous comments.

The signature provided is invalid. 

Please provide a signature for the latest commit sha: `108a786c57e2ab38c0a314e1ef8bc8b4b98c13a8` which must be signed with the owner wallet address: 
`erd1q3nzps6avwqsr8w830znr08y6uw7ausqzjcc3eczzg7qk7vaa9rschvzx5`

Thanks.

**Comment by pErsten** [comment]
{
  "address": "erd1q3nzps6avwqsr8w830znr08y6uw7ausqzjcc3eczzg7qk7vaa9rschvzx5",
  "message": "0x34363265386361613637623363653636666366303636353962663936616237656537356537343430",
  "signature": "0x9b6004f8fe808d90be22d5fce5afc66aec54737a097ec8b48d43f435d65a683b698842906d65d5d08c5a9ada2badafa16ce138a9ea568df0c5fedb8692f39b07",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
