### PR TITLE
Valoro: Fund Template

### PR DESCRIPTION
**Pull request by k05ta5**

### CODE REVIEW

**Comment by k05ta5** [comment]
{
  "address": "erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel",
  "message": "0x65726431717171717171717171717171717067717930686e37703063356b3471737a616577656a7435393838773463306e74793075377a73307979387775",
  "signature": "0x4b466ceb03156bb42c107d6659f728dc8eead6a7547ed1c1843b4841104803f5035b13b5e4be4270844d23df03625b9a04586e7bb852d06263ef52b3817e110a",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @k05ta5 

Please provide a signature for the latest commit sha: `8dea921fa911ca1377c1f771990756b0b74b1e94` which must be signed with the owner wallet address: 
`erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel`

Thanks

**Comment by k05ta5** [comment]
Hi @paulmultiversx ,

This one should be valid.

Thanks!

**Comment by k05ta5** [comment]
{
  "address": "erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel",
  "message": "0x38646561393231666139313163613133373763316637373139393037353662306237346231653934",
  "signature": "0xd27d2f3f3a3882af5f1346954ec205213dc86443142e32849ad4188cd81acd72049e46fefc61e1b802db2507e77b46eb742f125287717755365c9124762f9b06",
  "version": 1,
  "signer": "ErdJS"
}

**Pull request merged**
