### PR TITLE
Add assets for 'WENCAT-9e6a65'

### PR DESCRIPTION
**Pull request by wencatwen**

### CODE REVIEW

**Comment by wencatwen** [comment]
{
  "address": "erd1u9emmdv8lrm6flphcqcr9uffnm6zelw7yzm3wknunsjrd3qqhmmqz80evs",
  "message": "0x65363038653561313265613330386665303261633865646366646163343262323134336365313565",
  "signature": "0x022ee04ec596bcae22e70f7f8a643be41a5f8823149f4f08b771b88045484b4980adc1f39f0e2745d6b16ab2d49aa556a11ce1111e107addf017f3bbe953f105",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by wencatwen** [comment]
@paulmultiversx [🐱](https://emojipedia.org/cat-face)

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @wencatwen 

Hi, Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again:
https://jsonformatter.curiousconcept.com/ 
or
https://jsonlint.com/

Thanks

**Comment by wencatwen** [comment]
Hi @paulmultiversx 

Fixed

**Pull request merged**
