### PR TITLE
BOD Branding

### PR DESCRIPTION
**Pull request by Lallement-Kevin**

### CODE REVIEW

**Comment by Lallement-Kevin** [comment]
BOD's Owner signature :
{"message":"0x64616166303864653734303832353036643663643964633363623066356239373664393230623131","signature":"0x394569b46d5c56edcc5ff0362c2d8d55766dbcd003f59cb9be3199a5519714c589b4760f3de0016aedea9fe5880e3a9a1e7e13f5331745d8280a71ecc2b8530e","address":"erd1xkwc4jqjvuqrwxlz0h2uw87sf3cxrnxpf6z8ra2k0ax5thdmav4qtmds0a","version":1,"signer":"sdk-js"}

**Comment by batesondog** [comment]
SCAM ! this is not the real BOD,  This should not be tolerated, we are being robbed.

**Comment by Jotenks66** [comment]
> SCAM ! this is not the real BOD, This should not be tolerated, we are being robbed.

Just imagine if you actually used your talent for something useful. Here's you blatantly cancelling the PR once you're called out for being a scam and rebranding it to... impersonate BOBER. 

image


I can confirm the PR by @Lallement-Kevin is the genuine BOD.

**Comment by BubuMVX** [comment]
That's hilarious 🦉

**Pull request merged**
