### PR TITLE
Quasar SN: Strategic Nexus

### PR DESCRIPTION
**Pull request by QuasarMvX**

### CODE REVIEW

**Comment by QuasarMvX** [comment]
{
  "address": "erd1lm8ractajey2p4tf99vgt00jwdg9y7frsgsqeqjewcg4898453zsxkxrmu",
  "message": "0x34366630383338393738386465343139383061636461376431386361393661643564656539623363",
  "signature": "0xbf2891869925cb94e2460143c98cae89136061f4d88a4d31fdfe2a5640c0a238172ba6ef34159cb6011cda877eb3ea1b7a69b886a4b958452de4d45029f49409",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by QuasarMvX** [comment]
{
  "address": "erd1lm8ractajey2p4tf99vgt00jwdg9y7frsgsqeqjewcg4898453zsxkxrmu",
  "message": "0x65626462356133643633316632326662366165666363336162343134386365323933643132616232",
  "signature": "0x4db6bc5beb96aa4f621968669c822cf3b4ddf3c3c92d4bd7c4a66defa7d2dcb223b92a1112f5824bbf9710655cb452f11fe81740a46087a4a61046880e09320d",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @QuasarMvX 

You didn't signed the message with the owner wallet address.

Please provide a signature for the latest commit sha: `83768822f10411351d6521be314a3a9d16ca34a9` which must be signed with the owner wallet address: 
`erd1kuu3r0jhc46plzahuxwg65rvewx36ln7mwr8u6rjx43srhqs0k3s0a4eyl`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by QuasarMvX** [comment]
Hi! Sorry for that, we will sign all PR by each owner addres later tonight. 😀

**Comment by QuasarMvX** [comment]
{
  "address": "erd1kuu3r0jhc46plzahuxwg65rvewx36ln7mwr8u6rjx43srhqs0k3s0a4eyl",
  "message": "0x38333736383832326631303431313335316436353231626533313461336139643136636133346139",
  "signature": "0xff70a2c017171e58cd13dc36390354ae32f5c5426e8d209d442a1369a9251086814b502198691b4c81465d2c595c02d22aad61e2129ef7ae35baa2b827aaa706",
  "version": 1,
  "signer": "ErdJS"
}

**Pull request merged**
