### PR TITLE
fellowshipstaking

### PR DESCRIPTION
**Pull request by fellowshipcapital**
- add fellowship-staking identity
- change fellowship-staking logo

### CODE REVIEW

**Comment by fellowshipcapital** [comment]
0xb293b9870268444bde172fff24a7edc8887aae984e82ee0a4a2dadf9ee096d5c37a8d0c4c095d1d4bcc22bd9c1320bb90be958ec3594546d8c93d271ebe2bb08

**Comment by fellowshipcapital** [comment]
0x0a7594c9dfb3bcd33294dbe59f24f145df71c4772a83d009ac0418970c68382d558ccf423827f9bee0bc694ed340380ed73321003bd637fcdaa6a9685e0a5d05

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hi, @fellowshipcapital.

You have an invalid dimensions for your PNG (1280x1280)

The logo must have a resolution of 200x200 pixels and a max size of 100KB.

Please fix the issue so we can continue with the merging of this PR.

You can use the Assets dApp for this: https://assets.multiversx.com/

Thanks.

**Comment by fellowshipcapital** [comment]
0x9d5a1c371de3c5119214ed2d3fdb66da20b023a473da4202b9b8629cdc6309265d9f9c4cd7d55a99969c78654ea3191deda2b13feea0f9f1ef4b262f5f774a06

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
