### PR TITLE
CHARGED-703583

### PR DESCRIPTION
**Pull request by ionvv**
Branding for mainnet token `CHARGED-703583`

Branding for devnet token `CHARGED-fb7d88`

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ionvv.

Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Comment by ionvv** [comment]
> Hi, @ionvv.
> 
> Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR.
> 
> Thanks.

Thanks for quick reply, @paulmultiversx 🙏 
I've just synced it, should be good now

**Comment by paulmultiversx** [comment]
Hey, @ionvv.

This branch is out-of-date with the base branch. Please try again.

**Comment by ionvv** [comment]
> Hey, @ionvv.
> 
> This branch is out-of-date with the base branch. Please try again.

Seems that other PRs were merged in meantime. Synced again @paulmultiversx

**Pull request merged**
