### PR TITLE
Add assets for 'CRWEAPONS-e5ab49'

### PR DESCRIPTION
**Pull request by pErsten**
{
  "address": "erd1twt77wkq9cjfla6rxsmynqhznh272cfgvp846xmtj0u97see25xsmgxl4s",
  "message": "0x62616638393365623866643662383561356130303630613831376561373735363561316337383465",
  "signature": "0xfa9a60e8b4cdeb3cbb6a7cbb0fe3adf4dd7a8253a06e34786fe3d8ea061e4f2a8beec220e0316b20c53822326c3af55fb5323e1fbeee7d40df01f35cd939340b",
  "version": 1,
  "signer": "ErdJS"
}

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @pErsten

You have an invalid dimension for your logo.

logo.png must have a resolution of 200x200 pixels
max logo size 100KB

Also, the signature provided is not signed with the owner wallet address.

You need to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

**Review by paulmultiversx — APPROVED** [review]

**Comment by pErsten** [comment]
{
  “address”: “erd102975u07wnv0t8pl389l6dag2r9ca8ql2dsjvgc8jp59a39ycd4q4dsfdw”,
  “message”: “0x63656333323236333263383134313763653265326161643633376532656566356138343839643533",
  “signature”: “0x8f664a221e34513a570322c0669c0c9d709082e013358eb807f26661859d8b6f7d01cedad959030ab2b30e6b6771aeb20854ebd373adc4df1400b6defd13c00e”,
  “version”: 1,
  “signer”: “ErdJS”
}

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @pErsten 

Your logo has 210KB. Max logo size is 100KB as already stated in the previous comments.

The signature provided is invalid. 

Please provide a signature for the latest commit sha: `679ca1cd23df6d77b348b049588d6b7de5817b45` which must be signed with the owner wallet address: 
`erd1q3nzps6avwqsr8w830znr08y6uw7ausqzjcc3eczzg7qk7vaa9rschvzx5`

Thanks.

**Comment by pErsten** [comment]
{
  "address": "erd1q3nzps6avwqsr8w830znr08y6uw7ausqzjcc3eczzg7qk7vaa9rschvzx5",
  "message": "0x30393439343830363831613864616235343131623934303737323266643963343439653733633438",
  "signature": "0xacc2500ca350309a9a2edd6dd63957c45685b32253936acfd387f38f4a50ebd0f43f84fe9e4e8d4bd9706dd2b90d7775b125b678925b6ccec43319027fd87b0b",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
