### PR TITLE
Add assets for 'RUG-d86ff1'

### PR DESCRIPTION
**Pull request by RugSeal**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @RugSeal 

Please provide a signature for the latest commit sha: `1710a09a6b95b9417d5e6cba20f27edd89b39c75` which must be signed with the owner wallet address: 
`erd1j34ty6rjcxrmlur7jawn99cvwcqz9kx2tja9ytdunxsvke8ml3zqeufdtx`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by RugSeal** [comment]
Hi Paul, 
Not sure what I’m doing here can you tell? 
could you tell me what Information I need to put in what relevant box please? Started this project underestimating the workload. 
sign message - 
Verify signature -
Signed message - 
Signature -
kind regard 
WB

IMG_8002
IMG_8001

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hey, @RugSeal 

You need to sign (in the dedicated Sign message field) this commit hash: `1710a09a6b95b9417d5e6cba20f27edd89b39c75`

**Comment by RugSeal** [comment]
Could you share a link, I’m lost again. 
thank you!

**Comment by paulmultiversx** [comment]
Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

**Comment by RugSeal** [comment]
Hello again, sorry if this is wrong! I’m sort of just winging it at this point, trial by fire.  
In this the signature? 
477f5e303d5b79637802ceecd8f341ee0242555a1603a1334123fb096908c043c6b3215ca211c474278bf3b8f359ebd10e3531588a06307c68f0274d489b7d00
Kinda regards 
WB

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
