### PR TITLE
TIM2BUILT-88119f

### PR DESCRIPTION
**Pull request by ISTIMTOBUILT**

### CODE REVIEW

**Comment by ISTIMTOBUILT** [comment]
[info.json](https://github.com/multiversx/mx-assets/files/14725251/info.json)
logo
logo

**Comment by ISTIMTOBUILT** [comment]
[info.json](https://github.com/multiversx/mx-assets/files/14725255/info.json)

**Comment by ISTIMTOBUILT** [comment]
{
  "address": "erd1creqc9dpn2tuuuhxrsyhs7nc6jnycda6lucdz5zse432asfjltks2e26nd",
  "message": "0x38353866623133376439393665633336323031303165653231343131303231313862373334363639",
  "signature": "0x38f6d6014a92ede9ffd61451d95ae19f3987aef16aeb5a06da4aa72e29216b4c4087f24f25448365007f98f0c6befcababca260d66096a5df7da917378528908",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ISTIMTOBUILT 

Hi, Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again:
https://jsonformatter.curiousconcept.com/

Your PR must have 3 files and all the files need to be added in the Tokens directory.

You can use the Assets dApp for this: https://assets.multiversx.com/

Add in the comments only the signature. 

Once it's done, feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks.

**Pull request closed without merging**
