### PR TITLE
Add assets for 'XTW-78700a'

### PR DESCRIPTION
**Pull request by Azerus972**

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hi, @Azerus972.

Please grow your community to reach the minimum requirements in terms of followers before we can approve this PR, following the guidelines to maximize the chances of passing through the filters, which are in place to create a healthy and sustainable token ecosystem: https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Let me know once you have an update on this area.
Thanks.

**Comment by paulmultiversx** [comment]
Hello, @Azerus972. Once you've checked all the requirements, please make sure you update to the following structure your .json file:

{
  "website": "",
  "description": "",
  "social": {
    "twitter": "",
  },
  "status": "active"
}

**Comment by Azerus972** [comment]
Hello @paulmultiversx 
Tikaw is now attached to Sensei Ecosystem !
Let me know if you need any kind of other infos

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hey, @Azerus972.

Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again:
https://jsonformatter.curiousconcept.com/
https://jsonlint.com/

Thanks

**Comment by Azerus972** [comment]
@paulmultiversx Hello there seems fixed now

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
