### PR TITLE
Add assets for 'MILEI-512f95'

### PR DESCRIPTION
**Pull request by EnriMoreno**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @EnriMoreno 

Please provide a signature for the latest commit sha: `d09ee77015a28f2e3e97d340f7625ff2af971065` which must be signed with the owner wallet address: 
`erd17gl8j2f0zqjcxatrmedea48yxk96avk2nw7zu59gvyup0prevvdq6vmjqw`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by EnriMoreno** [comment]
I cant´t branding my token? why? which problem? help please

**Comment by paulmultiversx** [comment]
@EnriMoreno of course you can. But you need to provide a signature in order to prove you are indeed the owner of the token. This is something that every owner must do in order to have the PR merged.

So I will share instructions once again: You need to access the https://utils.multiversx.com/ and use the Sign Message feature, then paste the signature provided here in a comment.

You need to sign this commit sha: 'd09ee77015a28f2e3e97d340f7625ff2af971065' which must be signed with the owner wallet address: 'erd17gl8j2f0zqjcxatrmedea48yxk96avk2nw7zu59gvyup0prevvdq6vmjqw'.

Thank you

**Comment by EnriMoreno** [comment]
IMG_20240605_175045

hello. thanks for answering. I signed. result: valid signature.... and now?

**Comment by EnriMoreno** [comment]
hello. thanks for answering. I already verified the signature. result: valid signature.... and now?

**Comment by EnriMoreno** [comment]
signature:

0x62042a3ae4f3831cdce47cdb5ebd71b6f416132d9fd288e3101b06dffa6fd39f3503736b1fade14be320f78c3a7a71aebd243934811e1530c3769c6b18ba2601

**Comment by EnriMoreno** [comment]
{
  "address": "erd17gl8j2f0zqjcxatrmedea48yxk96avk2nw7zu59gvyup0prevvdq6vmjqw",
  "message": "0x64303965653737303135613238663265336539376433343066373632356666326166393731303635",
  "signature": "0x62042a3ae4f3831cdce47cdb5ebd71b6f416132d9fd288e3101b06dffa6fd39f3503736b1fade14be320f78c3a7a71aebd243934811e1530c3769c6b18ba2601",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
