### PR TITLE
Add assets for 'WOJAINU-2e01e4'

### PR DESCRIPTION
**Pull request by WOJAINU**

### CODE REVIEW

**Comment by WOJAINU** [comment]
8fdf8ffcc7d87dd20aab3b8ac0140e3886eed7754660173274c946025f83d8a9ccd399126492649c24db4a311f43da038a42d3996ef0b43bd22b6925b1b7b305
https://utils.multiversx.com/sign-message?signature=8fdf8ffcc7d87dd20aab3b8ac0140e3886eed7754660173274c946025f83d8a9ccd399126492649c24db4a311f43da038a42d3996ef0b43bd22b6925b1b7b305&message=f022d1f0f0d011f3932842c237fee17751f8062a&address=erd1uyh8yg9lcgxvnjqfw69dm25d92tu0mhxrw78xjjh2vuzc6dm3m6qcjd44h

**Comment by paulmultiversx** [comment]
Hi, @WOJAINU.

Your branch has conflicts that must be resolved

Conflicting files: 
tokens/WOJAINU-2e01e4/info.json
tokens/WOJAINU-2e01e4/logo.svg

Please fix the issue before we can further proceed.

Thanks.

**Comment by WOJAINU** [comment]
hello again ! :)

could we Verify our NFT collection ?

NFT Collection: WJX-31a722

**Comment by paulmultiversx** [comment]
Hey, @WOJAINU. Please create a new PR for your collection, because the previous one had conflicting files as well.

Thanks

**Comment by WOJAINU** [comment]
i don't want to be a pain in the @ss :) but when i open MVX assets i have
no option/button to add another or something like that ..

i will attach a screen capture


~NOTE:  i want to verify a NFT collection not a token

**Comment by paulmultiversx** [comment]
You need to create a fresh PR on Assets dApp containing all 3 files for your NFT collection: https://assets.multiversx.com/

**Pull request closed without merging**
