### PR TITLE
Add assets for 'swigsstaking'

### PR DESCRIPTION
**Pull request by swigsstaking**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @swigsstaking 

Please provide a signature for the latest commit sha: `b429131eae64129082321edf09e5ba6903ff27de` which must be signed with the owner wallet address: 
`erd1zd0gz6tuxjsn6ws5sgmdyt8u59tn9q2vmavmx8qxvjddhfgryyvqdc2r7n`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by swigsstaking** [comment]
Hi, all done
￼




Corentin Flaction
Tél. +41792926616
***@***.***
www.swigs.ch


SWIGS SA
Route de Saclentse 385
CH - 1950 Saclentse
***@***.***
www.swigs.ch

**Comment by paulmultiversx** [comment]
Hi, @swigsstaking 

You need to actually paste the signature here in a new comment in order to pass the Github check.

Thanks.

**Comment by swigsstaking** [comment]
0xff3f4ede53c17ac61583e8f8460e09969685010087c64e6e10796646bac7be7e067ff39853a411844502935c8e8938ade67e9ecc562994d83fc87f89026f9e09
￼




Corentin Flaction
Tél. +41792926616
***@***.***
www.swigs.ch


SWIGS SA
Route de Saclentse 385
CH - 1950 Saclentse
***@***.***
www.swigs.ch

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
