### PR TITLE
Add assets for 'DUNE-c4f2ff'

### PR DESCRIPTION
**Pull request by DuneToken**

### CODE REVIEW

**Comment by DuneToken** [comment]
Hi Paul,
Signature made in https://utils.multiversx.com/ although I see in each form
frame Signature VALID, I am not sure if I need to make any other actions
here, since I it dosen't get back a successful message closing the frame.

Thanks, have a great day

**Comment by paulmultiversx** [comment]
Hey @DuneToken 

You need to actually copy & paste the resulting signature here in a new comment.

Thank you

**Comment by DuneToken** [comment]
{
  "address":
"erd124dczvxzn4kvdw9xxv5mg7euvcjr8c0sdh2w5hx5gl7w8va2hcnqzey2dk",
  "message":
"0x68747470733a2f2f6170692e6769746875622e636f6d2f7265706f732f6d756c746976657273782f6d782d6173736574732f6973737565732f323330352f636f6d6d656e7473",
  "signature":
"0xcfbc413654f5d283ef04e434c5e562c7ba2692f0831b8eb5a7abe10b6d092c1c0239be77c551b91747dbb3abb1606f687faa4e0adae3c736e49e9805d9058900",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hey, @DuneToken 

You need to sign this commit hash: '0b1eb8548f0127fa340f02079bf2f37444f85973' and paste the signature in a comment

**Comment by DuneToken** [comment]
09f396b6bcaf29f70c0842d4a74a07add2b1bd16f037791705241b1a2475026f545bb0494326ab05b1a6b8f9fce2dd45af92a7c2a675a6106fb1717e70ad550a

**Pull request merged**
