### PR TITLE
RAPT token branding

### PR DESCRIPTION
**Pull request by florescu123**

### CODE REVIEW

**Comment by florescu123** [comment]
@arelrond any feedback?

**Comment by RTM12934** [comment]
the first 3D collection in Elrond awaits its token. What do you guys say?

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @florescu123.

Please review the issues above si and re-submit your PR. 
(Invalid dimensions for PNG! ( 500x500)

Thanks.

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
It appears you still have the same issue. Please create a fresh PR with the correct file dimension this time.
Thanks.

**Pull request closed without merging**
