### PR TITLE
BMPASS-989598

### PR DESCRIPTION
**Pull request by ucoralin**
Hello there. Please help me with branding this NFT (SFT) collection. Thank You!

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ucoralin 

Your logo.svg is too large! (180 KB)

Max size is: 100KB

Please fix it so we can continue with the merging of this PR.

After you've replaced it, please provide a signature for the latest commit sha: `6a15621f32f1fd695710c54dabcb918ad087ef46` which must be signed with the owner wallet address: `erd1t9jykg9xz47f5c087nqqlc5el7pcfpt3tc2hyqs6vwe463yntq9sp5cq4v`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature here in a comment: https://utils.multiversx.com/

Step-by-step guide:

Step 1: Copy latest commit sha
Step 2: Open: https://utils.multiversx.com/
Step 3: Log in with your owner address wallet
Step 4: Click the 'Sign Message' feature
Step 5: Paste the commit sha in the first column and hit sign
Step 6: Copy-paste the provided output signature here in a new comment

Thanks.

**Comment by ucoralin** [comment]
logo

**Comment by ucoralin** [comment]
{
  "address": "erd1t9jykg9xz47f5c087nqqlc5el7pcfpt3tc2hyqs6vwe463yntq9sp5cq4v",
  "message": "0x36613135363231663332663166643639353731306335346461626362393138616430383765663436",
  "signature": "0x2eb4a878d0ae351820edf554478de308e115668d7178cd045364f289311306cd9444f39afee321a1a7faa9a9b103cbf9d83d0134abe530c9e6ac54eada34680d",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by paulmultiversx** [comment]
@ucoralin it appears your json file is not valid.

Please validate it with a dedicated tool like this one, before you upload it again:
https://jsonformatter.curiousconcept.com/
https://jsonlint.com/

Thanks

**Comment by ucoralin** [comment]
Ok, sorry for that. All good now!

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
