### PR TITLE
Add assets for 'HOKI-94830b'

### PR DESCRIPTION
**Pull request by CosminBaluta**

### CODE REVIEW

**Comment by CosminBaluta** [comment]
kind reminder

**Comment by CosminBaluta** [comment]
kind reminder

**Review by arelrond — APPROVED** [review]

**Comment by arelrond** [comment]
Hello @CosminBaluta - please review the above errors and re-submit.

Thank you!

**Review by arelrond — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @CosminBaluta.

Please work on your holders number then create a new PR following the guidelines to maximize the chances of passing through the filters, which are in place to create a healthy and sustainable token ecosystem: https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Thanks.

**Comment by CosminBaluta** [comment]
Hei @paulmultiversx, i don't like to be "that guy", i usually stay focused on 'my backyard', but it's hard not to notice the discrepancy when others pass through those filters like it's nothing. 

Random example: 
- vesta token, approved in the same day, 268 holders, 489 tx. 
- hoki token, pending for 4 months, 332 holders, 831 tx. 

Thank you.

**Pull request closed without merging**
