### PR TITLE
Add assets for 'WOJAINU-2e01e4'

### PR DESCRIPTION
**Pull request by WOJAINU**

### CODE REVIEW

**Comment by WOJAINU** [comment]
7a98fd87cd9ea013fc46ecd2215c7851d124e8e305984ab06f6322161026434934693bda6922000432c20b7c863f467bc79203716ff1a399c0d79badadfb6e0b
https://utils.multiversx.com/sign-message?signature=7a98fd87cd9ea013fc46ecd2215c7851d124e8e305984ab06f6322161026434934693bda6922000432c20b7c863f467bc79203716ff1a399c0d79badadfb6e0b&message=ec5f84310e929f0a40490055c3fa5c03387fda3e&address=erd1uyh8yg9lcgxvnjqfw69dm25d92tu0mhxrw78xjjh2vuzc6dm3m6qcjd44h

**Comment by paulmultiversx** [comment]
Hi, @WOJAINU. 

Your branch has some conflicting files. Please create a new PR directly from Assets dApp: https://assets.multiversx.com/

Thanks.

**Comment by WOJAINU** [comment]
from dapp i made every upload..

**Comment by paulmultiversx** [comment]
Yes, we've made some updates on the process and you should not have conflicting files anymore.

**Comment by WOJAINU** [comment]
Ok, thanks for the clarification. i will try again right now . have a nice
day ! MVX 4 Life :D

**Pull request closed without merging**
