### PR TITLE
Branding DMXT-c47816

### PR DESCRIPTION
**Pull request by DecentralizedMxToken**
Add assets for DecentralizedMxToken

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Slerfmvx

We cannot approve this PR because it is against the official MX Assets Guidelines regarding the trademarks.

'logo does not resemble MultiversX/Mobile Wallet logos or other trademarked visual identities'

So, please eliminate the MVX logo from your logo and we will be able to proceed. 

Thank you for understanding.

**Comment by DecentralizedMxToken** [comment]
Hi @paulmultiversx 
I've removed the MVX logo from my design as per your request. Please check and let me know if we can proceed or if further adjustments are needed. Thank you for your guidance on this.

**Comment by paulmultiversx** [comment]
Hi, @DecentralizedMxToken 

Yes, the logo is OK now but you have 4 files in your PR now and you only need 3 files, the ones in your Tokens directory. 
Please delete the .vscode so we can proceed with the merging of this PR.

Thanks.

**Comment by DecentralizedMxToken** [comment]
@paulmultiversx 
Ok. .vscode file deleted

**Comment by paulmultiversx** [comment]
@DecentralizedMxToken - There are still 4 files in your PR. I recommend you close this one and start a fresh one if you don't manage to fix it.

**Comment by DecentralizedMxToken** [comment]
Trying again.

**Pull request closed without merging**
