### PR TITLE
Add assets for EVOAG-1a4f7d

### PR DESCRIPTION
**Pull request by allecks93**

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @allecks93. 

Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again: https://jsonformatter.curiousconcept.com/ 
https://jsonlint.com/

Thanks

**Review by paulmultiversx — APPROVED** [review]

**Comment by allecks93** [comment]
Hello @paulmultiversx!

The json file has been checked with the tools you provided and is valid.

Do I have to do anything else? 
Thank you

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hey, @allecks93. 

First, you need to delete the ledgerSignature field. 

Next, your json fields need to have this elements: 
"required": [
    "website",
    "description",
    "status"
  ],

You're missing the 'status' field in your json. Please make the necessary corrections and let me know once it's done. 
Thanks.

**Comment by allecks93** [comment]
Hello, @paulmultiversx! 

Sorry for the mistakes, I've fixed it now and everything should be fine!
Thanks!

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
