### PR TITLE
Add assets for 'QDAX-426435'

### PR DESCRIPTION
**Pull request by ElrondCrypto**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ElrondCrypto 

Please provide a signature for the latest commit sha: `7a279bc98c6292dcfb25d7e0877a704a169b39ea` which must be signed with the owner wallet address: 
`erd1hd2fq6g8tp63g5y5p0ujmemsa57ks4v7sqhhlcdhf42svt988leqsrphsx`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by ElrondCrypto** [comment]
Hello friend.
Could you detail what I need to do now.

**Comment by ElrondCrypto** [comment]
Done, waiting

**Comment by paulmultiversx** [comment]
@ElrondCrypto you need to actually paste the signature here in a new comment. Thanks

**Comment by ElrondCrypto** [comment]
signature":"0x087673113633922746114b8539ade380d97c308b398d9a31350b02aa4b519a3d7c6bf6d1907264142dad1f81a264039e36d74e52d581b5a5d17ddca2c2220e01",
Signature validated.
Thank you for the patience.

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
