### PR TITLE
CryptGain Ecosytem

### PR DESCRIPTION
**Pull request by newtmex**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hey, @newtmex.

You have an invalid dimensions for your PNG file ( 1367 x 1441 ).

logo.png must have a resolution of 200x200 pixels

Please fix it so we can further proceed with the merging of this PR.

Thanks.

**Comment by newtmex** [comment]
@paulmultiversx I have updated the branch with the recommendation.

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hey, @newtmex.

You still have some issues with your files. Please make sure you upload the PNG at the correct dimension.

_PNG dimensions: 1367 x 1441
Invalid dimensions for PNG! ( 1367 x 1441 )_

**Comment by newtmex** [comment]
Done

**Comment by newtmex** [comment]
@paulmultiversx Done

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
