### PR TITLE
Valoro WAGMI Fund SC & Token

### PR DESCRIPTION
**Pull request by k05ta5**

### CODE REVIEW

**Comment by k05ta5** [comment]
I sign the commit hash using the my wallet which is the owner of all Valoro SCs. 

TheWAGMI Fund SC and the corresponding token WAGMI, both have Valoro SCs as owners, for which I am the owner. Thus, I signed using my wallet which you can verify it's the actual owner of all the SCs.

**Comment by k05ta5** [comment]
{
  "address": "erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel",
  "message": "0x35346330393963623331356664303563363237343131356237616563333032323133316335636166",
  "signature": "0xfe26836eebef6e82794fb40717b5332d85e4d7c46f70a1eedd22991b584b1583e768f4becd6b4cb8cf50955d75c1826d1a196f27a5ba20fde10f0000999d5d0e",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hey, @k05ta5 

It seems your SVG file is not a square (w:1025 x h:1024)

We have a limitation at only 1 asset / PR so please split it in separate PRs.

Please make the necessary changes so we can proceed with the merging of this PR.

Thanks.

**Comment by k05ta5** [comment]
Ok @paulmultiversx , thanks!

**Pull request closed without merging**
