### PR TITLE
Update SnoopDoge description

### PR DESCRIPTION
**Pull request by CiozZ**
"Snoop" is enough as character.

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @CiozZ 

Please provide a signature for the latest commit sha: `75fad12fddd5d050b28dab51cb837f9907ac3758` which must be signed with the owner wallet address: 
`erd1qqqqqqqqqqqqqpgqcpvcgjtaffqpxwpurwhtua4xrj6xjzm9984s2azgjx`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature here in a comment: https://utils.multiversx.com/

Step-by-step guide:

Step 1: Copy latest commit sha
Step 2: Open: https://utils.multiversx.com/
Step 3: Log in with your owner address wallet
Step 4: Click the 'Sign Message' feature
Step 5: Paste the commit sha in the first column and hit sign
Step 6: Copy-paste the provided output signature here in a new comment

Thanks.

**Comment by paulmultiversx** [comment]
Hey, @CiozZ 

We can bypass the need for the owner address wallet (MemeversX) signature, allowing the process to be completed using the creator's wallet instead.

So please provide a signature for the latest commit sha: '75fad12fddd5d050b28dab51cb837f9907ac3758; which must be signed with the owner wallet address:
'erd1z7tceldhgmaxlllathtnlat9808mdccjc0jju0yek75yrsqr2lrs43jvqz'

Feel free to use the Sign Message feature from the Utils dApp and paste the signature here in a comment: https://utils.multiversx.com/

Step-by-step guide:

Step 1: Copy latest commit sha
Step 2: Open: https://utils.multiversx.com/
Step 3: Log in with your creator address wallet
Step 4: Click the 'Sign Message' feature
Step 5: Paste the commit sha in the first column and hit sign
Step 6: Copy-paste the provided output signature here in a new comment

Thanks.

**Comment by CiozZ** [comment]
Hi Paul

Message signed.
Here the output signature:

{
  "message": "37356661643132666464643564303530623238646162353163623833376639393037616333373538",
  "signature": "b0adecbacd20c6059d08dfd86cee5194bf4d2776d2532c3311e46a46588fa3c4af4c9a52ce3516d0a569a75a452a1ade7980c3e3eb13a1851c867a1ecf6fd703",
  "address": "erd1z7tceldhgmaxlllathtnlat9808mdccjc0jju0yek75yrsqr2lrs43jvqz",
  "version": 1,
  "signer": "extension"
}

Thanks!

**Comment by CiozZ** [comment]
{
  "message": "37356661643132666464643564303530623238646162353163623833376639393037616333373538",
  "signature": "b0adecbacd20c6059d08dfd86cee5194bf4d2776d2532c3311e46a46588fa3c4af4c9a52ce3516d0a569a75a452a1ade7980c3e3eb13a1851c867a1ecf6fd703",
  "address": "erd1z7tceldhgmaxlllathtnlat9808mdccjc0jju0yek75yrsqr2lrs43jvqz",
  "version": 1,
  "signer": "extension"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
