### PR TITLE
Add assets for 'XPHUNK-5e2eb6'

### PR DESCRIPTION
**Pull request by ccxspace**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hi, @ccxspace 

Please provide a signature for the latest commit sha: `f531ab553e3bde7532309ec0214c95b247e79cff` which must be signed with the owner wallet address: 
`erd19kkm3jr4axlvj70egpvlp35w6aqemvtt22kq43zx6ndvxyl329zqxzh3xk`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

**Comment by ccxspace** [comment]
> Hi, @ccxspace
> 
> Please provide a signature for the latest commit sha: `f531ab553e3bde7532309ec0214c95b247e79cff` which must be signed with the owner wallet address: `erd19kkm3jr4axlvj70egpvlp35w6aqemvtt22kq43zx6ndvxyl329zqxzh3xk`
> 
> Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/
> 
> Thanks a lot!

{
  "address": "erd19kkm3jr4axlvj70egpvlp35w6aqemvtt22kq43zx6ndvxyl329zqxzh3xk",
  "message": "0x66353331616235353365336264653735333233303965633032313463393562323437653739636666",
  "signature": "0xc4d4a41bd55ea83dd58674a3abf6416c14acc8aee9c3d3b508917ec3e7b0004b143691ff4713e6d71ddc2a9aecf243cee6676af38e14ad38ac3abab8d6c4080c",
  "version": 1,
  "signer": "ErdJS"
}


Thanks to you too !

**Review by paulmultiversx — APPROVED** [review]

**Comment by ccxspace** [comment]
is there anything else i need to do ?

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Yes, you need to make sure you're signing it with the owner wallet address.

**Comment by ccxspace** [comment]
> Yes, you need to make sure you're signing it with the owner wallet address.

i thought i did ?

**Comment by ccxspace** [comment]
0xc4d4a41bd55ea83dd58674a3abf6416c14acc8aee9c3d3b508917ec3e7b0004b143691ff4713e6d71ddc2a9aecf243cee6676af38e14ad38ac3abab8d6c4080c

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
