### PR TITLE
EMR Wrapper SC

### PR DESCRIPTION
**Pull request by Toderean**
{
  "address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
  "message": "0x65643364383038303864323136363731613063313466366530646565336536663363613231616334",
  "signature": "0x214bda30b7de5382449beb81c68a1943431a711c3b2f6f1ff4b2a82717c0bd7ce141ee7c7ecd8d5aca3e3c1b4f42b195db5471858fa5ba26b888b61a64f50c0a",
  "version": 1,
  "signer": "ErdJS"
}

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Toderean 

Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Comment by Toderean** [comment]
{
  "address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
  "message": "0x64376634333837383162343066663433356261343530646134326164613537643530643532306639",
  "signature": "0xc5433ba711a55025266e7dd0a46be96ed52b5ee154cc0e6bed39a382304635265a064b3ad23272a53da1f963ccc6652c1b96b37579cffe6f3c29f0e61e8d9f00",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
@Toderean One of your files includes a space. 

You currently have: accounts/ erd1qqqqqqqqqqqqqpgqrdkz05f3lfpf9csn7ck35xtl6pcmgec0mp3s4cwsp3.json

You should have: accounts/erd1qqqqqqqqqqqqqpgqrdkz05f3lfpf9csn7ck35xtl6pcmgec0mp3s4cwsp3.json

**Comment by Toderean** [comment]
{
  "address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
  "message": "0x66393832396435656164353136333931383233613137396665653466373134353466303930666533",
  "signature": "0x26dd2d5cc9342da9480795b54856ea48a13de7eb5187757039eda4fbb410ea4f03d595fda615359e2f8be7a27636bca462befe5fc25ac635df76715b044a4f0d",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by Toderean** [comment]
Latest update.
{
  "address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
  "message": "0x33626366393132373937386538363863373464353331613939646233386237656338613833356430",
  "signature": "0x80aa90e295ce4768ecfc8233d6337c4f4c1c0a0f1a265980856b793b229d9ae2b8aba6c56d1288bcc56d3a55624fc645861b14ee05f4f49c0e95b570efaef00c",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by paulmultiversx** [comment]
@Toderean it seems this branch has conflicts that must be resolved. You need to manually resolve the conflicts. In case you don't know how to do that, then just erase the fork from Github and re-start the process clean.

Thanks.

**Comment by Toderean** [comment]
It is possible somehow to delete the `erd1qqqqqqqqqqqqqpgqrdkz05f3lfpf9csn7ck35xtl6pcmgec0mp3s4cwsp3.json` file from the master branch because it is wrong named?

**Pull request closed without merging**
