### PR TITLE
Update_description_and_socials_ONE-f995df

### PR DESCRIPTION
**Pull request by alexjilavu**
0xa1ca27945bd1e7486e46a9c894d5769a0a78372d89bb6f3551865a98b7adfd7bf6197e3846e7c87aaa0c94ab332cd5cb4049abab2840c8e2aa5a2ea3aae04108

### CODE REVIEW

**Review by schimih — APPROVED** [review]

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hi, @alexjilavu.

Please provide a signature for the latest commit sha: `ecd9607c3dc97fd637bb98a8e4c46ec966d5a02b` which must be signed with the owner wallet address: 
`erd1xkflzkx3hp52szy26zh9m5ts3v3j4dxhqkpxzj9npzp7wyp6qeysfpqz2m`

Feel free to use the Sign Message feature from the Utils dApp: https://utils.multiversx.com/

Thanks.

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hei, @alexjilavu.

Please leave a comment with the signature for the latest commit sha: `ecd9607c3dc97fd637bb98a8e4c46ec966d5a02b` which must be signed with the owner wallet address: 
`erd1xkflzkx3hp52szy26zh9m5ts3v3j4dxhqkpxzj9npzp7wyp6qeysfpqz2m`

Thanks.

**Comment by alexjilavu** [comment]
> Hei, @alexjilavu.
> 
> Please leave a comment with the signature for the latest commit sha: `ecd9607c3dc97fd637bb98a8e4c46ec966d5a02b` which must be signed with the owner wallet address: `erd1xkflzkx3hp52szy26zh9m5ts3v3j4dxhqkpxzj9npzp7wyp6qeysfpqz2m`
> 
> Thanks.

added

**Comment by paulmultiversx** [comment]
Hey, @alexjilavu.

Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Comment by alexjilavu** [comment]
> Hey, @alexjilavu.
> 
> Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 
> 
> Thanks.

synced

**Pull request merged**
