### PR TITLE
Add assets for contract erd1qqqqqqqqqqqqqpgqqljsc0pfthe9jlmwuzvujqyxrdx89j0dtt0s6g6vpx

### PR DESCRIPTION
**Pull request by varun345**

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hey, @varun345.

Using the owner address of the identity, please sign/use the (Message Signing feature). It represents the latest commit hash of this PR. You should add a comment to this PR with the obtained signature. This is a step that ensures the ownership of the address. After that, we will be able to merge this PR.

Thanks.

**Comment by varun345** [comment]
Hi @paulmultiversx  , Sorry for late response . As per your last reply like you said to use Sign/use ( Message Signing Feature ). Here I'm going to add detail 

{
  "address": "erd1xprphj43dz5w7dsnvwlyg4edmkxcldwv7cgd3ws9wucazy5ctt0suf9d76",
  "message": "0x48656c6c6f20566172756e",
  "signature": "0x5481a1746df425eb835d79c0ce0f6b553470a2a0d35a6b00414577218914b5fe57351be9930e8c5ebd55a113b1d8a55d024cdb37194644e3874ba00fccd69d0a",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by varun345** [comment]
@paulmultiversx  Hi I am still waiting for your response. Could you please merge this PR

**Review by paulmultiversx — APPROVED** [review]

**Comment by varun345** [comment]
Hi @paulmultiversx  , I requested for branding my Smart Contract with this name "Xloans:Lending Protocol" , but Still my smart contract branding name not reflecting on Mainnet Explorer . Could you please check for issue ?  Smart Contract " erd1qqqqqqqqqqqqqpgqqljsc0pfthe9jlmwuzvujqyxrdx89j0dtt0s6g6vpx "

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hey, @varun345.

Can you please rename the tags with lowercase so we can continue with the merging of this PR? Thanks.

**Comment by varun345** [comment]
Hi @paulmultiversx , I renamed the Tag with lowercase. Could you please check once .

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
