### PR TITLE
Add assets for 'QDAX-426435'

### PR DESCRIPTION
**Pull request by ElrondCrypto**

### CODE REVIEW

**Comment by ElrondCrypto** [comment]
Please disregard previous calls, we had problems with the website address, this change today will be final, thank you.

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ElrondCrypto 

Please provide a signature for the latest commit sha: `45727730c1377a14130a30d2503cf76a70f2de87` which must be signed with the owner wallet address: 
`erd1hd2fq6g8tp63g5y5p0ujmemsa57ks4v7sqhhlcdhf42svt988leqsrphsx`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by ElrondCrypto** [comment]
ownership verification performed: 0x3e6d93e365a0fe58ba4d595faf44239d06142cbed4f052d70778343ffe1d5e2dd6f65b9daffb8bc2f70a5f25ae8a5637923992356811dbd711e1d8a08d802f06

**Review by paulmultiversx — APPROVED** [review]

**Comment by ElrondCrypto** [comment]
I congratulate the entire Multiverx team in the person of Beniamin, Lucian Mincu and Lucian Todea
for the initiative to build a Blockchain for everyone.
May this project bring peace, prosperity and health to the team, community and supporters.
May God bless us all.

**Pull request merged**
