### PR TITLE
Add assets for 'CHIBBY-dfdbb3'

### PR DESCRIPTION
**Pull request by DoubZer**

### CODE REVIEW

**Comment by DoubZer** [comment]
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x66306232663832306562636465343538346565623466643139316462323433373135383061363439",
  "signature": "0xa84313f4acb924b9a1cb8290feb79cc8fabfd5463e88706e852e49dbc5b378fd4acf3f3ad5247c9e8a556d6dce10e53b9fd17e830e7f9a49644167ed3fb0870b",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by DoubZer** [comment]
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x66306232663832306562636465343538346565623466643139316462323433373135383061363439",
  "signature": "0xa84313f4acb924b9a1cb8290feb79cc8fabfd5463e88706e852e49dbc5b378fd4acf3f3ad5247c9e8a556d6dce10e53b9fd17e830e7f9a49644167ed3fb0870b",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by DoubZer** [comment]
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x61353431353137373739636535386231653030313330366133366661316166323739363733316333",
  "signature": "0xee9ab1394a50b9cf7bc945de80fcd63700609af0a75c9259eed450860a7c971ea05b4c278e1393f66cf2e3ab27f67f6f749e896fd8ef42aecca53d5d5673850b",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by DoubZer** [comment]
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x32646166336662643266666535303131376432666631363638643935346163343662393536643338",
  "signature": "0xb742831822b619b873aedefacd516a68afc16ad920dafbcf9a0e23f65ff34633173c19930abe6981183503b186059b7b97777448cbd3878705728a432e1c7702",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by DoubZer** [comment]
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x38646463383037343237396465306532363530323337323338666437643966336333643735343030",
  "signature": "0x1d58cccb31e08a4b791d0d1e92ab3acca9eb623df85316d75200b763d5b38b10778f000c7f8b53ce086fc96515569445da20f78b27af3202d56b303d8042d100",
  "version": 1,
  "signer": "ErdJS"
}

**Review by DoubZer — COMMENTED** [review]
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x31393137663530393831613237643537356233616663363965336464303566396566373838383337",
  "signature": "0x3ee01e352912576f5346d0473d7711a06df6283b8862131de24aa4fa11ba5fd641c625e07a0e9f63cda7959d79ae6af22cd62f1fa37d13b6628fc03223042e0a",
  "version": 1,
  "signer": "ErdJS"
}

**Review by DoubZer — COMMENTED** [review]
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x65396336383333373535363434353765663866623962313839363630306630383064313139303332",
  "signature": "0x8603d8e9a928633596125cf4cee813ea0fa1d836c82d070676f1c5559b07dd5295c459146bc04b2ac94ad6212a22e0014f932c4e5d2a0569cbb77250d13f5003",
  "version": 1,
  "signer": "ErdJS"
}

**Review by DoubZer — COMMENTED** [review]
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x38646463383037343237396465306532363530323337323338666437643966336333643735343030",
  "signature": "0x1d58cccb31e08a4b791d0d1e92ab3acca9eb623df85316d75200b763d5b38b10778f000c7f8b53ce086fc96515569445da20f78b27af3202d56b303d8042d100",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by DoubZer** [comment]
signature for the latest commit sha:
{
  "address": "erd192jlr26zcw0c3xcehfrgqhgcm3avm6968z5tl89e7wtu9qdvkpdqfn4h32",
  "message": "0x38646463383037343237396465306532363530323337323338666437643966336333643735343030",
  "signature": "0x1d58cccb31e08a4b791d0d1e92ab3acca9eb623df85316d75200b763d5b38b10778f000c7f8b53ce086fc96515569445da20f78b27af3202d56b303d8042d100",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
