### PR TITLE
XMPH-3af949

### PR DESCRIPTION
**Pull request by MORPHESDT**

### CODE REVIEW

**Comment by MORPHESDT** [comment]
{
  "address": "erd1rfs4pg224d2wmndmntvu2dhfhesmuda6m502vt5mfctn3wg7tu4sk6rtku",
  "message": "0x36316139346134653532343631353934383366663538653165373438303937383665643238383464",
  "signature": "0xf10918b21add6c7431252c3d47dc77ac34aaa8180aa5f47cdca9b3ace250fd87d1c8840d2cd0579174dfdf2f58773a51b901623d9fd933331d7174652c821606",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by MORPHESDT** [comment]
{
  "address": "erd1cwt0rw5aqgcfn85pp3lv88x6expfj8zjh5jat5w4dhc7fg044fzqnfhs7t",
  "message": "0x36316139346134653532343631353934383366663538653165373438303937383665643238383464",
  "signature": "0x9266b1eaedc5454d5bbb48fcc3a3be2610db8800a86babd53f8ac4fa7d1ae0cb673bec227c47c6c1d5772008560d82dc3196b99a61c728a2832a284c7ba7e409",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hi, @MORPHESDT.

Hi, Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again:

https://jsonformatter.curiousconcept.com/
https://jsonlint.com/

Thanks

**Comment by MORPHESDT** [comment]
Hello,

Should be ok now.
Thanks.

**Pull request merged**
