### PR TITLE
Add assets for 'WOJA-ac90ab'

### PR DESCRIPTION
**Pull request by WOJAINU**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @WOJAINU 

Please provide a signature for the latest commit sha: `0ec15e9eeced98757766034c592ce2dd5661e306` which must be signed with the owner wallet address: 
`erd1uyh8yg9lcgxvnjqfw69dm25d92tu0mhxrw78xjjh2vuzc6dm3m6qcjd44h`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by WOJAINU** [comment]
Signed.

**Comment by paulmultiversx** [comment]
Hi, @WOJAINU 

You need to paste the signature here in a new comment.

**Comment by WOJAINU** [comment]
i've made < the merge >  you can now approve the PR #3262

**Comment by paulmultiversx** [comment]
@WOJAINU the PR cannot be approved if it doesn't pass the Github checks for the signature ownership.

Please have a look at this PR as an example and see how they provided the signature signed with the owner address wallet. 

You must do the same using our Utils dApp: https://utils.multiversx.com/

**Comment by WOJAINU** [comment]
{
  "address": "erd1uyh8yg9lcgxvnjqfw69dm25d92tu0mhxrw78xjjh2vuzc6dm3m6qcjd44h",
  "message": "0x30656331356539656563656439383735373736363033346335393263653264643536363165333036",
  "signature": "0x573b1a020bbef1ca92a5543b1f5ba07e1611aab4c52f807561ee2b1ce7ddf61ec93c1eda76a6bdb35ee2eb76ef87bd0835fa4dc3a9f888c3475a9107684e9500",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by WOJAINU** [comment]
i've left a reply on github but if i try from utils something is not
working well. did i do ok with the message ? it's enough for approval ?
thanks

**Pull request merged**
