### PR TITLE
Add assets for 'DELG-bc644a'

### PR DESCRIPTION
**Pull request by Delgtoken**
Hi ! Thank you for your review :)
Long live the DELG

### CODE REVIEW

**Comment by Delgtoken** [comment]
Message signed: `c8ee94791fe52c6fa1b31606b836d54a8b5f4330`

```json
{
  "address": "erd1lnuvvp4taq4m0m6zf7e32av2md322dvy675zlqhvd2pj9tkalesqxv0yne",
  "message": "0x63386565393437393166653532633666613162333136303662383336643534613862356634333330",
  "signature": "0x6e19cbc509340bb35c51e04519d938b807ec6c751dc22de51f2d6e611b26d01aa53fbf4694e731b89f33ea4a462bdf2ce2ef1e0b4ac8c4b4530ca53c9f1ae809",
  "version": 1,
  "signer": "ErdJS"
}
```

**Comment by Delgtoken** [comment]
2da9ebf3ddf78eb378d8ca37e3ea7dcabe83d4d9fd50148bcb8270acd15de7dd96f954809ab6716bfd30e17c4a090478ca90abd9ec78c7644afbeca45bbeca0b
```json
{
  "address": "erd1x45vnu7shhecfz0v03qqfmy8srndch50cdx7m763p743tzlwah0sgzewlm",
  "message": "0x36366536616632643934323561396537633565366331353032303933353463613939383933393866",
  "signature": "0x2da9ebf3ddf78eb378d8ca37e3ea7dcabe83d4d9fd50148bcb8270acd15de7dd96f954809ab6716bfd30e17c4a090478ca90abd9ec78c7644afbeca45bbeca0b",
  "version": 1,
  "signer": "ErdJS"
}
```

**Comment by Delgtoken** [comment]
Hi @bogdan-rosianu 👋 Sorry to ping you, do you think you could review this PR ? Many thanks 🙏🙏

**Comment by Delgtoken** [comment]
commit signed: 5b7cbe89680e6d06817e37539335dd721648f35f
```
{
  "address": "erd1lnuvvp4taq4m0m6zf7e32av2md322dvy675zlqhvd2pj9tkalesqxv0yne",
  "message": "0x35623763626538393638306536643036383137653337353339333335646437323136343866333566",
  "signature": "0x5362eee0a1f259a4ee87ee20c90feceeb647cc4bfbfb576e0ae91b5d61edd664552496e47a9a4c4877d75d872c8dce73b15305b3b7d77964903983e7c40ce80d",
  "version": 1,
  "signer": "ErdJS"
}
```

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
