### PR TITLE
Mainnet Branding Katon.io  KTON (KTON-e1626e)

### PR DESCRIPTION
**Pull request by loic-combis**

### CODE REVIEW

**Comment by loic-combis** [comment]
fff41287af2e8eed3362680a9c318df0b01cca9959004d74e7981c7c8202784082d9ee23d6ea087993b68b48a77e8f32803d11c15c13de2b009666f851f03009

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @loic-combis. 

You have achieved the necessary token holders and that is good progress, now you need to grow your community to reach the minimum requirements in terms of followers. Please read the guidelines to maximize the chances of passing through the filters, which are in place to create a healthy and sustainable token ecosystem: https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Thanks.

**Comment by loic-combis** [comment]
@paulmultiversx, we have over 7k people that actually created an account and downloaded our wallet on mobile. Doesn't this count?

**Comment by paulmultiversx** [comment]
Hey, @loic-combis.

Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR.

Thanks.

**Comment by loic-combis** [comment]
Done! @paulmultiversx 

Thanks

**Pull request merged**
