### PR TITLE
Disruptive Digital testnet ID

### PR DESCRIPTION
**Pull request by disruptivedigital**

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hey, @disruptivedigital.

Please add the logo.svg in the PR as well.

Thanks.

**Comment by disruptivedigital** [comment]
0x83fb16ea279abe8f9f1dfc2fd3d688a95e1556272ea79f6ab0cd5d39f6f4e316043663cea5d2213d4ecca5a70234f2b79080fd1d6442b52e90c6374ae86bc204

**Comment by disruptivedigital** [comment]
> Hey, @disruptivedigital.
> 
> Please add the logo.svg in the PR as well.
> 
> Thanks.

Done! do I need to sign with the latest commit hash again?

Thank!

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Yes, please sign the latest commit hash of this PR.

**Comment by disruptivedigital** [comment]
0x476a5ae0f656e8d3c4c264252c24a6cddb1849b0a747e2be5b6f0188c61a9e32f30a845668bc4fe1bd521de5cddf0f9aaff40364edeec778d86388f4d55d0200

**Review by paulmultiversx — APPROVED** [review]

**Comment by disruptivedigital** [comment]
I don't understand what I do wrong 🤷‍♂️. I double checked the latest commit hash and the signature and seems all right.

**Review by paulmultiversx — APPROVED** [review]

**Comment by disruptivedigital** [comment]
0x5db7dcbb6d354694bb1efe689566f6e9a0e6ce579b393f8fc6e21af89c2ef86bec3967ebab45327a8b921fb8b9ff248d99cf410fad0b481f53a88244e09e100d

**Review by iulianpascalau — APPROVED** [review]

**Pull request merged**
