### PR TITLE
Update info.json

### PR DESCRIPTION
**Pull request by pos4d4**

### CODE REVIEW

**Review by pos4d4 — COMMENTED** [review]
Updated locked accounts

**Comment by pos4d4** [comment]
https://github.com/multiversx/mx-assets/pull/3224/commits/d974392f34ace1357487c485c9e70cc4bcc265f0

{
  "address": "erd1g3ufcfdlnpamunzpaa4kutg3z7y9vtuqm3twpkh57ye2ppycgenseekdcl",
  "message": "0x68747470733a2f2f6769746875622e636f6d2f6d756c746976657273782f6d782d6173736574732f70756c6c2f333232342f636f6d6d6974732f64393734333932663334616365313335373438376334383563396537306363346263633236356630",
  "signature": "0xee1a91e689356333a2d3272f97cd2751da107b171a77fbb275c722aaa047ad0442462ffea4fb973cb8f26cd3051d92d1054d18da22a4db141a4c1c540371c608",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Review by pos4d4 — COMMENTED** [review]
Updated json

**Comment by pos4d4** [comment]
https://github.com/multiversx/mx-assets/pull/3224/commits/bad1405968df25ccf3aa630a122484f6a455e5ff

{
  "address": "erd1p25pluvfx4yny4hsedxvufh3ky7m4s3crhtxhqukcd2m8clfzpcslxdp99",
  "message": "0x68747470733a2f2f6769746875622e636f6d2f6d756c746976657273782f6d782d6173736574732f70756c6c2f333232342f636f6d6d6974732f62616431343035393638646632356363663361613633306131323234383466366134353565356666",
  "signature": "0xb2e6ced0bf57988c6db873a7854d91a90cdf139c680f30943bda4c3876f3c8ee0ae55598048eaf01093773d5fa4e398e3783236760245e3636ceffe2da64a405",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
