### PR TITLE
 LPXMPHJEX-f5090f

### PR DESCRIPTION
**Pull request by MORPHESDT**
Regards

MorphTok

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by MORPHESDT** [comment]
{
  "address": "erd1rfs4pg224d2wmndmntvu2dhfhesmuda6m502vt5mfctn3wg7tu4sk6rtku",
  "message": "0x37373038656538643238386637323863373263623931316237396239373062316139336462363837",
  "signature": "0xcb38456b243cf495f4ebceaff20ed1f95b80c52c913bc577a5966105953a28520b4e114e5ce85b38d720a92dc7ae279b8a8e13cf46acfeb818f5d413eda30401",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by MORPHESDT** [comment]
{
  "address": "erd1rfs4pg224d2wmndmntvu2dhfhesmuda6m502vt5mfctn3wg7tu4sk6rtku",
  "message": "0x62316434306339376532653965393435326639353133663733663765623666393863646362663064",
  "signature": "0xfb5a99aecb88fb92c2118eaffd0587a61331b478d431a94b3c924f44a0296c679bf95fa7cb96065a27503534b35dbe6a243c1c2e1a06230d92e3dc8a245cba0f",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by MORPHESDT** [comment]
Files renamed as required.
Regards

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hi, @MORPHESDT.

You have an invalid dimensions for PNG! ( 200 x 204 )

logo.png (must have a resolution of 200x200 pixels) 

Please the issue before we can proceed with merging of this PR. Thanks

**Comment by MORPHESDT** [comment]
It's done Paul.
Regards

**Pull request merged**
