### PR TITLE
Plata Network ESDT Stake

### PR DESCRIPTION
**Pull request by PlataColdWallet**
….json

Plata Network Standard ESDT Stake

### CODE REVIEW

**Review by PlataColdWallet — COMMENTED** [review]
SC description

**Comment by paulmultiversx** [comment]
Hey, @PlataColdWallet.

Using the owner address of the identity, please sign/use the (Message Signing feature). It represents the latest commit hash of this PR. You should add a comment to this PR with the obtained signature. This is a step that ensures the ownership of the address. After that, we will be able to merge this PR.

Thanks.

**Comment by SergiViP** [comment]
{
  "address": "erd16hw82y4dsq3226kyjcnacjrsqxxvy7ervpmqrzr4g3wygzkt0pnq9mt5qa",
  "message": "0x68747470733a2f2f6769746875622e636f6d2f6d756c746976657273782f6d782d6173736574732f70756c6c2f313732322f636f6d6d6974732f36383565646264303037396231306130306433393230303832336432343734613736643932666532",
  "signature": "0xb143f1acc421c8386d4f5917ee1c073c2a7fbbdab8efb108ecbe6d29a6cc85de8cff72ac792c1d1d8f981b2954d46e2c88b97f390089ea6ccf9cc735bd139104",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by PlataColdWallet** [comment]
{
  "address": "erd1l8qmksyvfgn60hqhqgucufzx5adp4kny8gf07vypmgytyxqcgr9q3u6jnk",
  "message": "0x68747470733a2f2f6769746875622e636f6d2f6d756c746976657273782f6d782d6173736574732f70756c6c2f313732322f636f6d6d6974732f36383565646264303037396231306130306433393230303832336432343734613736643932666532",
  "signature": "0xb4ac13b1dcdeccd5c053eb768b280ff552ab407c7b37d4a9162be8b39304a62f029d93ae45fb6f020c73388139a82f8659b6ba33c9166a44eec189278cd73101",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by PlataColdWallet** [comment]
{
  "address": "erd1l8qmksyvfgn60hqhqgucufzx5adp4kny8gf07vypmgytyxqcgr9q3u6jnk",
  "message": "0x68747470733a2f2f6769746875622e636f6d2f6d756c746976657273782f6d782d6173736574732f70756c6c2f313732322f636f6d6d6974732f36383565646264303037396231306130306433393230303832336432343734613736643932666532",
  "signature": "0xb4ac13b1dcdeccd5c053eb768b280ff552ab407c7b37d4a9162be8b39304a62f029d93ae45fb6f020c73388139a82f8659b6ba33c9166a44eec189278cd73101",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
