### PR TITLE
update erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqs8llllsa3xsu3…

### PR DESCRIPTION
**Pull request by tcavacean**
… metadata

### CODE REVIEW

**Comment by tcavacean** [comment]
0xa523fb4627a12e2838e80a8a2c0df2cf0693f0d4468ee212f8e3128a8c46464c09119bea6bb9a6ea58d3f358869ee1d34c16c70c013f590dc11127e9b01af201

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @tcavacean 

You have an invalid dimension for your PNG. (1024 x 1024)

logo.png (must have a resolution of 200x200 pixels) 
max logo size 100KB

Please re-upload it properly so we can proceed with the merging of this PR.

Thanks

**Comment by tcavacean** [comment]
@paulmultiversx  Thanks for pointing this out, the changes have been made.

**Comment by tcavacean** [comment]
0x5f22905d19995cdc16b192d0383bc2df62de068d71c3e7e1d09e0cab8980d711f0c820ab25c718e71612f24cf18f0648bf28c2db42b1d31125d312a7b2ab8b0e

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
