### PR TITLE
Add assets for 'SANTAMUERT-6bbf1a'

### PR DESCRIPTION
**Pull request by n0xNFT**
Hello team,

Please add the branding for our Santa Muerte collection!

Thanks,
n0x

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @n0xNFT 

Please provide a signature for the latest commit sha: `205a2104759bc10bc60c5d0638631736f89f3a65` which must be signed with the owner wallet address: 
`erd1qqqqqqqqqqqqqpgqg9fa0dmpn8fu3fnleeqn5zt8rl8mdqjkys5s2gtas7`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by n0xNFT** [comment]
Hello Paul,

{
  "address": "erd1agvsg8rme2y3wmvdmyvx5ugtr30csm3x848nx9nf5qcsgc0qvgtq2ctta4",
  "message": "0x32303561323130343735396263313062633630633564303633383633313733366638396633613635",
  "signature": "0x95bc87e7287bcf87e441d6777765645592873ca663d89f29e4bdda22775f20ad2b293469bb79afbc3753d0c627ca92a2dcea3b441accf529b7671cd487447b01",
  "version": 1,
  "signer": "ErdJS"
}

signed with the creator wallet used on the Xoxno Launchpad.

thanks,
n0x

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @n0xNFT 

It appears the signature is not valid since it was not signed with the wallet owner address - the SC of XOXNO Launchpad. 

Try to sign it with this address instead and paste the signature provided: erd1p4gzmyha0qve47calgegujaa76nmregxldhq4s8rkt4t2wegwkpsn9vavu

**Comment by n0xNFT** [comment]
Hi Paul,

Here you go:

{
  "address": "erd1p4gzmyha0qve47calgegujaa76nmregxldhq4s8rkt4t2wegwkpsn9vavu",
  "message": "0x32303561323130343735396263313062633630633564303633383633313733366638396633613635",
  "signature": "0x2bcd5c119704a7d45625fa22a1c43a2c94a2c46267410aca0c83a3f55820dcf60a01c0f262368277cf5c19fc5736d6cb1f30f2ba0b99838ab06b861b6bf9ae07",
  "version": 1,
  "signer": "ErdJS"
}

Thanks,
n0x

**Pull request merged**
