### PR TITLE
JEX: update logo

### PR DESCRIPTION
**Pull request by javier-nft**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by javier-nft** [comment]
Here the signature:

`{
  "address": "erd1hmfwpvsqn8ktzw3dqd0ltpcyfyasgv8mr9w0qecnmpexyp280y8q47ca9d",
  "message": "0x61353531633935393935663832646135313262303364313739623138343138636261646533306165",
  "signature": "0x7039df77cca4dc3778d8a5e680e76b3c1487fe94bd210381f432e3a41c6a27abb3e391122e0dc7184854197fffc83833779d5f741f1f2c5eb6ab19afc787100f",
  "version": 1,
  "signer": "ErdJS"
}`

Thanks

**Review by paulmultiversx — APPROVED** [review]

**Comment by javier-nft** [comment]
0x7039df77cca4dc3778d8a5e680e76b3c1487fe94bd210381f432e3a41c6a27abb3e391122e0dc7184854197fffc83833779d5f741f1f2c5eb6ab19afc787100f

**Comment by paulmultiversx** [comment]
It seems this isn't the right signature. 

Please make sure you sign a signature for the latest commit sha: `a551c95995f82da512b03d179b18418cbade30ae` which must be signed with the owner wallet address: 
`erd1hmfwpvsqn8ktzw3dqd0ltpcyfyasgv8mr9w0qecnmpexyp280y8q47ca9d`

**Comment by javier-nft** [comment]
That's weird. I could verify the signature.

image

There's an HTTP 403 error while trying to access the comment:

image

**Pull request merged**
