### PR TITLE
Add assets for 'BATESDAO-d3effc'

### PR DESCRIPTION
**Pull request by BalooSuperRareBears**

### CODE REVIEW

**Comment by BalooSuperRareBears** [comment]
{
  "address": "erd1l3xnkmxhwfa2t668sdha7lzlmvqukawj54qrxvze4fj2tq47fkhse6pr08",
  "message": "0x33343332653239353132356465613266666166333830343831646535666435366366623634343236",
  "signature": "0x76334b2512be32ce02be6cb77b72ec4ade82b109ab1e07493b122e0977a2f3340c1a217cf4768ce1acea6ab2bc7e33c9f41378ddfe476fe355247dab0ea6c106",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @BalooSuperRareBears 

Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again:
https://jsonformatter.curiousconcept.com/
https://jsonlint.com/

Thanks

**Comment by BalooSuperRareBears** [comment]
Hi, @paulmultiversx 

The JSON file had a valid format. I checked it on both websites you mentioned. I believe 'website' was a mandatory field in the JSON and I've added it. Let me know if everything is fine now.

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
@BalooSuperRareBears all good now. All the best!

**Pull request merged**
