### PR TITLE
Add assets for 'ONX-3e51c8'

### PR DESCRIPTION
**Pull request by ilCriptonauta**

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hi, @ilCriptonauta 

Please provide a signature for the latest commit sha: `7434546aaf27f2e102968394066e2d4f80cab6ac` which must be signed with the owner wallet address: 
`erd1knr6ha4xat3juryp47x3duj4lykjhlxqhdu67vtj4ey9apy6aa5sg0hlem`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by ilCriptonauta** [comment]
Hi Paul, this is my first time that I try to verify an asset.
Can you kindly explain to me better what I should do? For both Artemis and
OnionX?

I designed both logos. Do I just have to sign? If yes, what should I do?


Il giorno gio 25 apr 2024 alle 15:16 Paul | MultiversX <
***@***.***> ha scritto:

**Comment by paulmultiversx** [comment]
Hi, @ilCriptonauta 

You need to go to https://utils.multiversx.com/ and perform the actions I suggested in the previous comment. Then paste the signature provided here in a new comment.

**Comment by ilCriptonauta** [comment]
420ee85a41d0a815ffb8cf3b6c53dc219d588f01a6ddc86c47f85733120f40c6ee03e43586549d5448921d8a0866970784ec71e65c7a38def7e961b023cf9301 

here my signature for ONX-3e51c8-assets-1714045896467

**Pull request merged**
