### PR TITLE
Kosmium Network branding

### PR DESCRIPTION
**Pull request by Monarchus**
We have modified our previous PR accordingly as requested by the @paulmultiversx. Please review. All the best.

### CODE REVIEW

**Comment by Monarchus** [comment]
logo

**Comment by Monarchus** [comment]
logo

**Comment by Monarchus** [comment]
logo

**Review by Monarchus — COMMENTED** [review]
logo

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Monarchus.

You have an issue: File tokens/KOS-e0db9d/logo.svg is too large (288 KB).

Please lease create a new PR with 3 files & the correct dimensions.

Guidelines: https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Thanks.

**Comment by Monarchus** [comment]
We opened a new PR here--- Add assets for 'KOS-e0db9d' #1112

**Pull request closed without merging**
