### PR TITLE
Add assets for 'ARAB-3bf796'

### PR DESCRIPTION
**Pull request by ArabCatMVX**

### CODE REVIEW

**Comment by ArabCatMVX** [comment]
Arab Cat is waiting habibi 😽

**Comment by ArabCatMVX** [comment]
hi @paulmultiversx 

Could you please review our cute cat please

Thanks in advance!

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ArabCatMVX 

Please provide a signature for the latest commit sha: `6d9284f1fd10441b6ae2bd31f2ea9ececd6d9ccf` which must be signed with the owner wallet address: 
`erd1gke8an8dde3fuu4j4zdjwkr37fn4x0xr9pc7z6vrna6lrlcq6rks8azw8f`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by ArabCatMVX** [comment]
{
  "address": "erd1gke8an8dde3fuu4j4zdjwkr37fn4x0xr9pc7z6vrna6lrlcq6rks8azw8f",
  "message": "0x36643932383466316664313034343162366165326264333166326561396563656364366439636366",
  "signature": "0x2ea5644774d0828e89118c893c1117fe44e961da410ddb7cc14e378709e4a91e4dc4bcd69f68935300c76e1f05b66576f9b133d5e907882e7110990da795e406",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
