### PR TITLE
Add assets for 'BIDXBOT-9a8b6b'

### PR DESCRIPTION
**Pull request by Bidxx**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Bidxx 

Please provide a signature for the latest commit sha: `a04fe97217cf8dac3fcc16c31684ecb5f22eca4f` which must be signed with the owner wallet address: 
`erd1jqxcyggdxhjddx3zaare5xvr7kraeeg9uptrdt9a542c4wjzhe0qq3dung`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature here in a comment: https://utils.multiversx.com/

Step-by-step guide:

Step 1: Copy latest commit sha
Step 2: Open: https://utils.multiversx.com/
Step 3: Log in with your owner address wallet
Step 4: Click the 'Sign Message' feature
Step 5: Paste the commit sha in the first column and hit sign
Step 6: Copy-paste the provided output signature here in a new comment

Thanks.

**Comment by Bidxx** [comment]
adresa":"erdtjqxcyggdxhjddx3zaare5xvr7kraeeg@uptrdta

542c4wjzhe0qq3dung", „mesaj”: „0x613034666539373231 37636638646163336663633136633331363834656362356

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Bidxx 

As you can see the signature is not correct. Please follow the above shared instructions and copy-paste the entire output once you use the Sign message feature from the Utils dApp. 

Thanks

**Comment by Bidxx** [comment]
{
  "address": "erd1jqxcyggdxhjddx3zaare5xvr7kraeeg9uptrdt9a542c4wjzhe0qq3dung",
  "message": "0x6130346665393732313763663864616333666363313663333136383465636235663232656361346620",
  "signature": "0xcc0d6593ddbdc53ac7165c146a128ccd05734b520d2589a34144cdfc74b587f7e232d9140f176de5ff7c698285e122db36c14e49e4c7ed8866b715ead8b91f0d",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — APPROVED** [review]

**Comment by Bidxx** [comment]
@paulmultiversx 

{
  "address": "erd1jqxcyggdxhjddx3zaare5xvr7kraeeg9uptrdt9a542c4wjzhe0qq3dung",
  "message": "0x6130346665393732313763663864616333666363313663333136383465636235663232656361346620",
  "signature": "0xcc0d6593ddbdc53ac7165c146a128ccd05734b520d2589a34144cdfc74b587f7e232d9140f176de5ff7c698285e122db36c14e49e4c7ed8866b715ead8b91f0d",
  "version": 1,
  "signer": "ErdJS"
}

**Pull request merged**
