### PR TITLE
Add assets for 'DRAKARYS-bdcf1a'

### PR DESCRIPTION
**Pull request by DrakarisToken**

### CODE REVIEW

**Comment by DrakarisToken** [comment]
b4245d9b18f8d7fa9d083cf31817add210d2b85998e7516955f458af0ac10e46c0c20990b8cad8666c42854c62b7d5ecb0f9e1def0a52cd71a2ee03bb91d260e
https://utils.multiversx.com/sign-message?signature=b4245d9b18f8d7fa9d083cf31817add210d2b85998e7516955f458af0ac10e46c0c20990b8cad8666c42854c62b7d5ecb0f9e1def0a52cd71a2ee03bb91d260e&message=e90466794558d66ffc121936408978f74ad5dce5&address=erd14ykxncrv5hdt7lvqzrl4p5djy80426tjyn4g4pqfmf95yw9vxnnslv4xfr

**Comment by paulmultiversx** [comment]
Hi, @DrakarisToken 

Your logo.svg is invalid. Please update it properly.

Also, don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

**Comment by DrakarisToken** [comment]
{"address":"erd14ykxncrv5hdt7lvqzrl4p5djy80426tjyn4g4pqfmf95yw9vxnnslv4xfr","message":"0x4920616d20746865206f776e657220666f7220746869732077616c6c6574","signature":"0xf49d09213251fdab9872efe25e0c3507eaa444435a655d41c509b80255ee9d9216b8554798874990eab91e483b18ea0dba2d9fa1aa77125a7e7a844ba5ad4603","version":1,"signer":"ErdJS"}

**Comment by paulmultiversx** [comment]
@DrakarisToken You need to replace the empty logo.svg in the Tokens directory with the correct logo.

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @DrakarisToken 

Please provide a signature for the latest commit sha: `51891979f656624870882e9e81aa13be71164f67` which must be signed with the owner wallet address: 
`erd14ykxncrv5hdt7lvqzrl4p5djy80426tjyn4g4pqfmf95yw9vxnnslv4xfr`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by DrakarisToken** [comment]
> 51891979f656624870882e9e81aa13be71164f67

Hi @paulmultiversx 
I think its this what you mean. 

The signature:

9f7a70bec5b8656b983aee43451c0e9ab00eab804494d4743cbcda1c8268878b49e78017e5a8220d26bc73f324b6ca3bc62b65216c4a603d2e3779408d662202

If its not were do i find a tutorial on how to do it.
Thanks in advance.

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
