### PR TITLE
Add assets for 'WLRP-b3eec0'

### PR DESCRIPTION
**Pull request by AgentH4**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @AgentH4 

Please provide a signature for the latest commit sha: `d1f50d216efaf3ef50bea693e356a135892f0ba5` which must be signed with the owner wallet address: 
`erd1ezcwhwhl4m8jljwgmrw2ephmgkzq3k8f3wwd36hf28alpdc5uuzqunxua2`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by AgentH4** [comment]
{
  "address": "erd1ezcwhwhl4m8jljwgmrw2ephmgkzq3k8f3wwd36hf28alpdc5uuzqunxua2",
  "message": "0x65726431657a63776877686c346d386a6c6a77676d7277326570686d676b7a71336b386633777764333668663238616c7064633575757a71756e78756132",
  "signature": "0xf29c7d13d6d84dc21b57bacdbb1745de8ccec68c6a7878a5d7b7af0fdf2753cb362ed93b6987216d7ba2ec36a2f5ecb37796b7db452e3b40e60e38aac20f8903",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @AgentH4 

You need to the latest commit sha: 'd1f50d216efaf3ef50bea693e356a135892f0ba5' not the owner address. 

Please try again and paste the signature in a comment.

Thanks

**Comment by AgentH4** [comment]
{
  "address": "erd1ezcwhwhl4m8jljwgmrw2ephmgkzq3k8f3wwd36hf28alpdc5uuzqunxua2",
  "message": "0x64316635306432313665666166336566353062656136393365333536613133353839326630626135",
  "signature": "0x03f1537d1e3cb36b3bc326e690b0de26b67ea16bbcecfb8d3a5cfb429f2a2597f3664170ebc2493500f31d89613d3a433af9d30a6f4247e443919e1e70128d04",
  "version": 1,
  "signer": "ErdJS"
}

**Pull request merged**
