### PR TITLE
xshib account

### PR DESCRIPTION
**Pull request by ShibaversX**

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ShibaversX 

We have a limitation at only 1 asset / PR so please split it in separate PRs.

Also, don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks.

**Comment by ShibaversX** [comment]
{
  "address": "erd1w0wnnmcvmxj250ryz3tuhrs8v5rlqst4059uqzvfxw6e5hxl888q9pl0qs",
  "message": "0x64383437316630396331646261363437393836643563323230393162613236653161386237383236",
  "signature": "0xf609c97375f4184f413c73193e6135924fc0f0f1f5f89c644eacf00ade10d7aa9d3153a4e2abfdd5bbaf9aea60901f3a70be960bff6ea2c89798f7159d52b302",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ShibaversX 

It appears you didn't signed with the correct owner wallet address.

Please provide a signature for the latest commit sha: `124844f9b8cb2e754899b58825b496e02780e915` which must be signed with the owner wallet address: 
`erd10mujtwnp9dl99mw74xdqxwmf0gest6eq0axmwa90jp0uzatyfz3qum3hd0`

Thanks

**Comment by ShibaversX** [comment]
{
  "address": "erd10mujtwnp9dl99mw74xdqxwmf0gest6eq0axmwa90jp0uzatyfz3qum3hd0",
  "message": "0x31323438343466396238636232653735343839396235383832356234393665303237383065393135",
  "signature": "0x4eabbae7afa0d9017934d8180c56810accc4530a8c79558d660b8527c1bbf9ac9c0b167586b854f351c4fbfbf02bcc781398240acdfb9a872f4cd84341a12009",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
