### PR TITLE
Add assets for 'MM1E-4f04b9'

### PR DESCRIPTION
**Pull request by Timevtraveler1**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hi, @Timevtraveler1 

Please provide a signature for the latest commit sha: `3e849b0af8b1ff228b8274a614ab7abaa530a7b4` which must be signed with the owner wallet address: 
`erd1vnsh57pftq28ag3njjz5wvlx0f0c9ugph73l3k4m57ralejdsf8ql6q386`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

**Comment by Timevtraveler1** [comment]
{
  "address": "erd1vnsh57pftq28ag3njjz5wvlx0f0c9ugph73l3k4m57ralejdsf8ql6q386",
  "message": "0x65726431766e736835377066747132386167336e6a6a7a3577766c7830663063397567706837336c336b346d353772616c656a64736638716c3671333836",
  "signature": "0x85e1e33c59e34bd86faef5c56115606f1efc2e881017e68bbe4be6a749b371585c7c6f7344eb982621714ac660a695cbfff827a8936c50f54af1d06b9d022802",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Timevtraveler1 

It appears you didn't signed the latest commit sha: '3e849b0af8b1ff228b8274a614ab7abaa530a7b4' 

Please make sure you sign the commit sha, using your address wallet and then paste the signature in a new comment.

Thanks.

**Comment by Timevtraveler1** [comment]
{
  "address": "erd1vnsh57pftq28ag3njjz5wvlx0f0c9ugph73l3k4m57ralejdsf8ql6q386",
  "message": "0x33653834396230616638623166663232386238323734613631346162376162616135333061376234",
  "signature": "0x6e957ade2064d4769941e27a45ba097eda96d828b84cf1df75ef4bbb27660be91317aa0a096165076a92a538b70cdd4bc1382c4b7fc6e5437fec7f9922cd2a0f",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
