### PR TITLE
Checker

### PR DESCRIPTION
**Pull request by tanghel**

### CODE REVIEW

**Comment by cfaur09** [comment]
Please provide a signature for the latest commit sha: `0cc9ebac0fe2d47de230bd7f68c7ef72bf437ce2` which must be signed with the owner wallet address `erd1qnk2vmuqywfqtdnkmauvpm8ls0xh00k8xeupuaf6cm6cd4rx89qqz0ppgl`

**Comment by tanghel** [comment]
f719f88b1c5a636256ed3621fc2dbf78dd99864743530b996af6f87dd0d802bd2a22aa47e34f3efc60d4625e694b920dd23e05ac702573b26c17bec12ec29408

**Comment by cfaur09** [comment]
The provided signature is invalid. Please provide a signature for the latest commit sha: `0cc9ebac0fe2d47de230bd7f68c7ef72bf437ce2` which must be signed with the owner wallet address `erd1qnk2vmuqywfqtdnkmauvpm8ls0xh00k8xeupuaf6cm6cd4rx89qqz0ppgl`

**Comment by tanghel** [comment]
84e2e024efb91c1b88fd315863a1b4d005f80c0d8b19a8501bfc0babfc2b6170a9abd982a88fa9d1baaa2621d4739e6c717f2295a391538a4c025ac521c55c02

**Comment by cfaur09** [comment]
Signature OK. Verified that the latest commit hash `0cc9ebac0fe2d47de230bd7f68c7ef72bf437ce2` was signed using the wallet address `erd1qnk2vmuqywfqtdnkmauvpm8ls0xh00k8xeupuaf6cm6cd4rx89qqz0ppgl`

**Comment by cfaur09** [comment]
The provided signature is invalid. Please provide a signature for the latest commit sha: `dbf6f52e08ece6ebf5775f3cee32d8bfff75c004` which must be signed with the owner wallet address `erd1qnk2vmuqywfqtdnkmauvpm8ls0xh00k8xeupuaf6cm6cd4rx89qqz0ppgl`

**Review by cfaur09 — APPROVED** [review]

**Pull request merged**
