### PR TITLE
Add assets for 'ROAR-e5185d'

### PR DESCRIPTION
**Pull request by luxaway**

### CODE REVIEW

**Comment by luxaway** [comment]
hey boss i would love to unbrand ROAR-c31b6d at same time please i made an error while minting my first token

**Comment by luxaway** [comment]
{
  "address": "erd1yqu7lartn9wgp65kauq98d0mpfnncaes3q3he4wwr8esp5e3ljkqd5a03k",
  "message": "0x6662386535623139393838643664336132323235373864626262396235653439663532333339626420",
  "signature": "0x8abd81e4e0f2b784bedad6c2b3cc30b651fd8d4e82b12cca70b3938182278c2b203cdfe249bd91dfb8dbe76798cb70b65e03608e2777d521a8e0503e8ea3df0d",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by luxaway** [comment]
I see an error  on check asset ownership everything is good or not ?

**Comment by paulmultiversx** [comment]
As long as it fails, it is not OK. You need to sign it with the owner wallet address.

**Comment by luxaway** [comment]
But the owner adress is good its erd1yqu7lartn9wgp65kauq98d0mpfnncaes3q3he4wwr8esp5e3ljkqd5a03k

can you tell me whats the problem ??

**Comment by luxaway** [comment]
{
  "address": "erd1yqu7lartn9wgp65kauq98d0mpfnncaes3q3he4wwr8esp5e3ljkqd5a03k",
  "message": "0x66623865356231393938386436643361323232353738646262623962356534396635323333396264",
  "signature": "0x93ffd49c048a769d23ad635a58e30f1ea104fd24212919d3332d27dfb4a59762b31c369703d6168b89cac48b7714d68ae07a14efef14e619bc829d5e6785d803",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by luxaway** [comment]
Here is the signature payload

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
