### PR TITLE
XMPH-3af949

### PR DESCRIPTION
**Pull request by MORPHESDT**
This token is an evolution of the already branded token MPH-f8ea2b.

Regards

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hey, @MORPHESDT.

Can you please share your website and your social communities profiles so we can have a look? 

Thanks.

**Comment by MORPHESDT** [comment]
Hello Paul,

No website, no official socials.
But you can check this twitter thread https://x.com/xMorPH_ESDT/status/1552636225990938625?s=20
xMPH is just an evolution of MPH (already branded) because we found a way to mint more MPH (using localmint special role) and the promise of MPH was to be not mintable... So xMPH is now here to correct this issue (SetSpecialRole = NO) and we plan to allow people to switch each single MPH for an xMPH. Branding of xMPH is key for this operation.

Regards

**Comment by paulmultiversx** [comment]
Hey, @MORPHESDT. I understand. Thanks for sharing this information with me. Unfortunately we can not approve the merging of this new version of the token without passing the necessary filters, which are in place to create a healthy and sustainable token ecosystem. Part of this conditions are: 

1. Projects need to have a minimum of 1000 token holders and token transactions
2. Projects need to have a minimum of 1000+ Twitter, Discord or TG official channel followers
3. Projects need to have a working website

Full guidelines here:  https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Please let us know once you've checked all the requirements.
Thanks.

**Comment by MORPHESDT** [comment]
Hello,

We already know all these requirements since $MPH token is already branded.
We also know that there are lot of exception to these requirements.
We also know tokens which met these requirements and at the end were scams.
$xMPH token will never have official website nor social since it's part of its identity.
$xMPH branding will not threat ecosystem health or sustainability.

If you are afraid about tokens number inflation then you can unbrand $MPH and brand $xMPH instead.

Regards

**Comment by MORPHESDT** [comment]
Hello,
Holders are smoothly transitioning from $MPH to $xMPH.
$xMPH is now listed on Jexchange and Onedex.
$xMPH is even followed by Ecompass.
$xMPH is an evolution of $MPH (which is branded) and all $MPH will be swapped by holders in $xMPH.
That why we submit this branding request even if general requirement are not met so far.

Regards

**Comment by MORPHESDT** [comment]
Hey, @paulmultiversx , can you check again this PR?

**Comment by paulmultiversx** [comment]
Hey, @MORPHESDT. Your PR is still in pending phase, waiting for your updates on the requirements stated above. 

Thank you for understanding. 

Have a great day!

**Comment by MORPHESDT** [comment]
Hello @paulmultiversx 

These requirements will never been met as they were never met for $MPH token from which $xMPH is an evolution.
No socials, nor website is a core value of $xMPH token.
Please escaladate this PR to someone which is not appreciating PR only based on the official requirements. We have to set an exception for $xMPH based on arguments I shared to you 2 days ago.

Thanks for your understanding

HAve a great day too.

**Comment by MORPHESDT** [comment]
Hello @paulmultiversx,

Do you have any news about this PR approval ?

Regards

**Comment by MORPHESDT** [comment]
Hey @paulmultiversx ,

Hope this week will bring good news about this branding process.

Regards

Morphtok

**Comment by MORPHESDT** [comment]
Hello @paulmultiversx ,

Any update about this PR approval ?

Regards

MorPHtok

**Comment by MORPHESDT** [comment]
Hello @paulmultiversx ,

Are you attending Xday too?
Hope everything fine for you.

Expect a feedback on this PR after this huge event!
Enjoy.

Regards

MorPHtok

**Comment by MORPHESDT** [comment]
Hi @paulmultiversx ,

Can we moove forward on this PR ?

Warm Regards

**Comment by paulmultiversx** [comment]
Hey, @MORPHESDT.

Please understand that we can not approve the merging of this new version of the token without passing the necessary filters, which are in place to create a healthy and sustainable token ecosystem. Part of this conditions are:

Projects need to have a minimum of 1000 token holders and token transactions
Projects need to have a minimum of 1000+ Twitter, Discord or TG official channel followers
Projects need to have a working website
Full guidelines here:  https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

Please let us know once you've checked all the requirements. All the conditions are mandatory.
Thank you for understanding.

**Comment by MORPHESDT** [comment]
Hello @paulmultiversx 

Actually this is not true that these conditions are mandatory.
So, can you ask for a exceptionnal approval since this token is an evolution of MPH-f8ea2b wich is an already branded and historical token ?

Warm Regards

MorphTok

**Comment by MORPHESDT** [comment]
Hello @paulmultiversx,

Were you able to escaladate this PR approval to someone who can act out of process ?

As stated before, if the main issue is having an inflation of the number of branded tokens please consider my proposition to unbrand MPH-f8ea2b then brand XMPH-3af949 instead.

Have a nice WE

MorphTok

**Comment by MORPHESDT** [comment]
Hey @paulmultiversx

Any news ?

Regards

MorPHtok

**Comment by MORPHESDT** [comment]
Hello @paulmultiversx 

$MPH holders can't understand why $MPH token was branded and why it takes so long to have the $xMPH token branded.
Can we move forward on $xMPH branding process ? As stated multiple times and as a couterpart of this branding, we are fully opened about $MPH unbranding if it can speed up the process.

Regards

MorphTok

**Comment by MORPHESDT** [comment]
Hello @dragos-rebegea,

Can you have a look on this PR?

Regards

Morphtok

**Comment by MORPHESDT** [comment]
Hello @paulmultiversx, @dragos-rebegea,

Can you describe us the process which allow some tokens to be branded before passing the necessary filters ?
This PR is opened for more than 1 month now and we are stuck at the same point. 

PR is blocked due to $xMPH not passing the filters but some tokens are branded even if they don't met the requirements.
The idea behind these filters is to keep "a healthy and sustainable token ecosystem."  We don't think $xMPH is threatening tokens ecosystem since it's an evolution of $MPH which is already branded. Can you argue why you want to specifically keep this token unbranded ? What are the threats ?

About the 1 month period, we also noted thant some PR are validated under 2 or 3 days ? Why is it so long to escaladate this PR to someone who can approve it even if not fit with the filter ?

Kind regards,

MorphTok

**Comment by MORPHESDT** [comment]
Hi @paulmultiversx,

How are things evolving about this PR ?

Regards

MorPHtok

**Comment by MORPHESDT** [comment]
Hi @paulmultiversx 

Can we move forward on this PR?
Additionnaly to all we have said previously, please find here the link to your blog where it is stated that the filters mentionned above are not mandatory : https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

image

Can you have a look on this PR with all these arguments in mind?

Warm Regards

MorphTok

**Comment by paulmultiversx** [comment]
Hey, @MORPHESDT.

XMPH-3af949 is a completely new token. The requirements are not negotiable, they are mandatory.

Unfortunately we can not approve the merging of this new version of the token without passing the necessary filters, which are in place to create a healthy and sustainable token ecosystem. Part of this conditions are:

Projects need to have a minimum of 1000 token holders and token transactions
Projects need to have a minimum of 1000+ Twitter, Discord or TG official channel followers
Projects need to have a working website
Full guidelines here:  https://multiversx.com/blog/branding-esdt-tokens-nft-collections/

This PR will be closed now. You can create a new PR once you've checked all the requirements. 

Thank you for understanding.

**Comment by MORPHESDT** [comment]
@paulmultiversx 

The team who branded PADAWAN token was able to negociate these requirements.
Branding was done before reaching 1000 holders. We just want to have equal treatment of our request.
We all have lot of examples like that, just talking about the last one - We don't have anything against PADAWAN team.

Why some token are branded and some other not? 

Why do you say that these filters are mandatory since they are not : de jure based on your blog post, de facto based on at least 1 example we gave you.
Why can't you explain us what do you mean by : "healthy and sustainable token ecosystem" ?

We expect to have clear answers to these questions ?

Warm regards.

PS : Could you please reopen this PR since not fully processed ?

MorPhTok

**Pull request closed without merging**
