### PR TITLE
corrected logo files

### PR DESCRIPTION
**Pull request by fkingerd**
We have updated the logo files. 

Do we need to sign the commit again ?

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @fkingerd 

Your logo.svg file is too large. It has 412KB. 
Max size is 100KB. Please fix it and re-upload it properly.

Also, don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks

**Comment by fkingerd** [comment]
@paulmultiversx here is the message: 0xb2c24e457e508d601afde3c0161c3e69f0dc91f68232b3c6fa9ec1a9d071f8fbdf701a563d2b4829770011c498f29d786391014fd711963ff98c1e14681ca300

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @fkingerd 

Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Comment by fkingerd** [comment]
@paulmultiversx now we cool ?

**Comment by paulmultiversx** [comment]
100% cool

**Pull request merged**
