### PR TITLE
Add assets for 'colombiastaking'

### PR DESCRIPTION
**Pull request by colombiastaking**

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hey, @colombiastaking.

The pngFile is invliad and must be deleted. We have logo.png and that's where the image should be. Please fix it so we can proceed.

Thanks

**Comment by colombiastaking** [comment]
I added the logo and info.json file directly in the testnet folder and identities, creating the colombiastaking identity : the files are the same as the one used in mainnet identity.

let me know 

thanks

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @colombiastaking. 

There are 2 more steps before proceeding to the merging of the PR:

1. Please remove the `pngFile` field from `info.json`. It is not needed. After this, please commit the changes

2. Inside https://testnet-wallet.multiversx.com and using the owner address of the identity, use the Message Signing feature. You should sign the latest commit hash of the PR after pushing the other change. You should add a comment to this PR with the obtained signature. This is a step that ensures the ownership of the address. After that, we will be able to merge this PR.

Thanks.

**Comment by colombiastaking** [comment]
Should be signed now : 
I removed the other PR

{"address":"erd1hsmzwg3ml7mwtu4e27ux9qfrsw3cjcnqmr05ld7l6qzd99209u8qxkp9sn","message":"0x30653430616462326430356533646636633466616234376335343039386338336330373264663365","signature":"0x51088101446653828a42b5fe70c0ae8a20f60014b9217c8ca1e668134420441bd1d3faa06023a8fd6dc1c89813d58285179eb582ed2616f9702f2d33a88ec903","version":1,"signer":"ErdJS"}

**Review by paulmultiversx — APPROVED** [review]

**Pull request closed without merging**
