### PR TITLE
Add assets for 'RON-26a1a2'

### PR DESCRIPTION
**Pull request by pmarius6**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @pmarius6 

Please provide a signature for the latest commit sha: `4f8440e590b876dbc58fdb7c4380311db4e54db4` which must be signed with the owner wallet address: 
`erd1jes0a3ncpu78m99trhz95q0fsth2gvjp4v03l6wt7ckcnwngqj3qzmx0pc`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by pmarius6** [comment]
{
  "address": "erd1jes0a3ncpu78m99trhz95q0fsth2gvjp4v03l6wt7ckcnwngqj3qzmx0pc",
  "message": "0x657264316a65733061336e63707537386d39397472687a39357130667374683267766a70347630336c36777437636b636e776e67716a33717a6d78307063",
  "signature": "0x62c2c9e6aec0742d3130dba2fc78147a5d9ba272a1c34896b8ea06f168a93afb398a2387b9fb599121d3dd76efb7e7eb7284aa2b36cc8521d253753319d70301",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @pmarius6 

The signature provided is not correct. You need to provide the signature for the latest commit hash, not for the owner address.

Please provide a signature for the latest commit sha: `29e3af116674094e721a22b705c504a8b1130726` which must be signed with the owner wallet address: 
`erd1jes0a3ncpu78m99trhz95q0fsth2gvjp4v03l6wt7ckcnwngqj3qzmx0pc`

Thanks

**Comment by pmarius6** [comment]
{
  "address": "erd1jes0a3ncpu78m99trhz95q0fsth2gvjp4v03l6wt7ckcnwngqj3qzmx0pc",
  "message": "0x32396533616631313636373430393465373231613232623730356335303461386231313330373236",
  "signature": "0x93f47816e503133374578aecd455bb974c5e452cd6a082c97c22499971fa034856c9e0871e6c73ffa614a2185fa8db0589dbf8dfe600a60386d1f32b68da110f",
  "version": 1,
  "signer": "ErdJS"
}

I hope it's ok now.

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
