### PR TITLE
Update CHECKR token

### PR DESCRIPTION
**Pull request by anonbitco**
- [x] Logo updated
- [x] Description updated

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hey, @anonbitco.

File tokens/CHECKR-60108b/logo.svg is too large (204 KB)
Please reupload it to max 100KB in order to proceed with the approval.

Thanks.

**Comment by anonbitco** [comment]
Hi @paulmultiversx 
SVG logo size has been fixed.

Thank you.

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hey, @anonbitco.

Your PNG also has an issue with the size: Invalid dimensions for PNG ( 580 x 580 )

**Comment by anonbitco** [comment]
both logo fixed for dimension of 200 * 200
is only this dimension allowed?

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
