### PR TITLE
Add assets for 'EWIF-5e7fb1'

### PR DESCRIPTION
**Pull request by ElrondWifHat**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @ElrondWifHat 

Please provide a signature for the latest commit sha: `0be4d30e292c19f8611e8d32e8708a118bead175` which must be signed with the owner wallet address: 
`erd1kr9g2gsg9vdk96equuypd72jqrhvp3lx24xj9mpausexadu7sk4shavrpl`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

**Comment by ElrondWifHat** [comment]
d43fc4243e9462fad2464992deb6b78582a4028f392b96783ad60e0f4331bc41c2cb610648045c04743f740e71362c651fcd57fc2169608746c593f582d23002

**Review by paulmultiversx — APPROVED** [review]

**Comment by ElrondWifHat** [comment]
Hi @paulmultiversx 

Could you hit me up real quick about why one of the checks is not going through ?

Thanks !

**Comment by paulmultiversx** [comment]
Hi, @ElrondWifHat 

You're missing the logo.png file

Please update it so we can further proceed with the merging of this PR

**Pull request closed without merging**
