### PR TITLE
Add assets for 'SATOMI-7c27f5'

### PR DESCRIPTION
**Pull request by SatomiMvx**

### CODE REVIEW

**Comment by SatomiMvx** [comment]
Signature payload for latest commit:

{
  "address": "erd13jwjfdz2hggq28gcdut9j6j3ky9xjuxe7zju0ys5eu4hd69esgds6flkpm",
  "message": "0x37653134373939323363323139643630383563633737316236373631396639613536303863393937",
  "signature": "0x0f1a1bdfb2bdcbab94e6f2c3f906ef95b7899b1e5061d557a23e2d00f3183cf567b1b7dc064f8d69a5ec66f0843eb7994c1ac7f3c4a493f548a244c4288b9000",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by paulmultiversx** [comment]
Hi, 

Token with ticker SATOMI already exists! Existing token id: SATOMI-d2964e.

**Comment by SatomiMvx** [comment]
@paulmultiversx  I think you made a confusion, SATOMI-7c27f5 is a NFT and SATOMI-d2964e is a ESDT. Yes, I did use the same logos but they are 2 different Tokens.

**Comment by paulmultiversx** [comment]
@SatomiMvx my apologies, you are right ;)

**Pull request merged**
