### PR TITLE
Add assets for 'SLIP-fbb724'

### PR DESCRIPTION
**Pull request by v4nl33**
Hello guys!

Here is the signature "0xa8eb90825f5c8b1226f180946a4cde3c31f1214cdf5d3bded6b50f032f872c65baa324b134a59e9515709d16c57203de4f7879e4f9fd5bc504691ce793fdfc09"

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @v4nl33 

Please check your logo.svg

Also, your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Comment by paulmultiversx** [comment]
@v4nl33 your logo.svg  is an Invalid image source. Please re-upload it properly.

**Comment by v4nl33** [comment]
@paulmultiversx the logo.svg seems ok to me, I tested it in browser and it works. Why do you say it's Invalid image source?

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Token with ticker SLIP already exists! Existing token id=SLIP-785f50.

Please generate a unique token that hasn't been previously created.

Thanks

**Pull request closed without merging**
