### PR TITLE
Create info.json

### PR DESCRIPTION
**Pull request by pos4d4**

### CODE REVIEW

**Comment by pos4d4** [comment]
https://github.com/multiversx/mx-assets/pull/3228/commits/5730afba7db522e4e72adb3cfed03e8fde764422

{
  "address": "erd1g3ufcfdlnpamunzpaa4kutg3z7y9vtuqm3twpkh57ye2ppycgenseekdcl",
  "message": "0x68747470733a2f2f6769746875622e636f6d2f6d756c746976657273782f6d782d6173736574732f70756c6c2f333232382f636f6d6d6974732f35373330616662613764623532326534653732616462336366656430336538666465373634343232",
  "signature": "0x4d28c9b376e72d7fb2c84f2fe346f009269c69e312efbc4c0fb862678f1c99e1fd4caab682aaea3518d5101bffd571526ab84689343c6ddef6f1598003067a08",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by pos4d4** [comment]
https://github.com/multiversx/mx-assets/pull/3228/commits/75a8a0eebc80e48c5b3b83164adf203a8077dd41

{
  "address": "erd1g3ufcfdlnpamunzpaa4kutg3z7y9vtuqm3twpkh57ye2ppycgenseekdcl",
  "message": "0x68747470733a2f2f6769746875622e636f6d2f6d756c746976657273782f6d782d6173736574732f70756c6c2f333232382f636f6d6d6974732f37356138613065656263383065343863356233623833313634616466323033613830373764643431",
  "signature": "0x799f6882f126f333e02cace74119fd53603d52e76f84563e6f333d69fe035e19a394fcc1816bbb6af8be020e2d47652d66d2f1d688d00759754edc9036b8d30d",
  "version": 1,
  "signer": "ErdJS"
}

**Review by pos4d4 — COMMENTED** [review]
Updated locked account

**Comment by pos4d4** [comment]
https://github.com/multiversx/mx-assets/pull/3228/commits/d79d1e8f1a871c7fe2701e55c3c2b6f58f717bc0

{
  "address": "erd1g3ufcfdlnpamunzpaa4kutg3z7y9vtuqm3twpkh57ye2ppycgenseekdcl",
  "message": "0x68747470733a2f2f6769746875622e636f6d2f6d756c746976657273782f6d782d6173736574732f70756c6c2f333232382f636f6d6d6974732f64373964316538663161383731633766653237303165353563336332623666353866373137626330",
  "signature": "0x84f62814eb52f08ab9985cc5e6aa1c1a1f79549e8cec86fe2b9867e5dedb7e804c758ffff8efbcca88d4456b434471276c11a07a8482f142e06e5cea06eaf60b",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
