### PR TITLE
VICTOR-9fa27f tkn

### PR DESCRIPTION
**Pull request by FkngSer**
Hello @paulmultiversx ,

Please check and approve this PR where we added Victor token from SVU (Super Victor Universe) project.

Please find below the signature generated for the latest commit sha:
0x14b93d41ed0be58a16dce442c4bc0bd0a551eb27ffb94c9fe40f3b9c1b6b644f7796423ce72a114b6f6be19bc612dea6edf74fabbbb69ea6cc5d5e0da314ef09

### CODE REVIEW

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @FkngSer 

Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again:
https://jsonformatter.curiousconcept.com/
https://jsonlint.com/

Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Review by paulmultiversx — DISMISSED** [review]

**Review by FkngSer — COMMENTED** [review]
Done.

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
@FkngSer it appers the json file still has an issue. Please check it out and validate it with a dedicated tool like this one, before you upload it again:
https://jsonformatter.curiousconcept.com/
https://jsonlint.com/

**Comment by FkngSer** [comment]
I c my checks failed again regarding json file .... cannot find what the issue is. Validators said ok.

**Comment by FkngSer** [comment]
It is missing website key and since we wrote website1 and website2 the pile checks failed again regarding. I will fix asap

**Review by paulmultiversx — APPROVED** [review]

**Review by FkngSer — COMMENTED** [review]
Change so pipe will find website key

**Pull request merged**
