### PR TITLE
Valoro: Proxy

### PR DESCRIPTION
**Pull request by k05ta5**

### CODE REVIEW

**Comment by k05ta5** [comment]
{
  "address": "erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel",
  "message": "0x657264317171717171717171717171717170677171766a327a72646676346c7363333870386376683465307964346176366e6a6675377a736a377a747a6c",
  "signature": "0xff42c565727bd7539189c9bd53eec1ae65d684c5d22313786458f3b9081c028519888e1e5f04168ce39a7ea9ca07be1b0b23de2abfeb44d9044109ece085a705",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @k05ta5 

Please provide a signature for the latest commit sha: `ad2371ec5301cd23c3ed3ad431af782f329c8d37` which must be signed with the owner wallet address: 
`erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel`

Thanks

**Comment by k05ta5** [comment]
Hi @paulmultiversx ,

This one should be valid.

Thanks!

**Comment by k05ta5** [comment]
{
  "address": "erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel",
  "message": "0x61643233373165633533303163643233633365643361643433316166373832663332396338643337",
  "signature": "0x07f0c5bc682f7667ce693bc16b7cce997153485813c30a58657d70ce180430c1f775f0befd231a6b828562e39df92775e70aa3c24887699c915cc1e1511dc702",
  "version": 1,
  "signer": "ErdJS"
}

**Pull request merged**
