### PR TITLE
Create (Info.json) for xCHIBBY NFT collection

### PR DESCRIPTION
**Pull request by DoubZer**

### CODE REVIEW

**Comment by DoubZer** [comment]
Signature : aa2f21a4007e378b743b4404acce03cbe58c58104f66aa8ff39adf01838f66fe8341cd09cb84889f7502f65531e12bb456dacc2624f31bac9f15fb65515ad909

**Comment by DoubZer** [comment]
Signature : b3985e3f77ac2bb31524754513c52ce2a96dd76fd50983f79e8bf1491244f274676545dbffb046839d8c9509cbfc30d9d2dd39aae95651699a661c3b6d48c200

**Comment by DoubZer** [comment]
Signature : 
e2118c6c85e267505aa7928f0bce7fa685f992cb6a7ca8ea18102e32f537306dce41a943c3335dea2ca7c7bbfd7b62892ff97981d7a02cdc8124ff558b48f50d

**Review by paulmultiversx — DISMISSED** [review]

**Comment by DoubZer** [comment]
Hi, @paulmultiversx 

Thanks for your response.

I have modify :
- the logo png to 200 x 200 for 78 ko
- the info.json

But now there is 7 commits to merge .. I hope I did the right thing

Can you tell me how I can carry out the verification to have the gold checkmark on the explorer MultiversX for our collection NFT ?

Thanks in advance

**Comment by DoubZer** [comment]
Signature : 5cdd34e1ea73b23c28b55acb289d49374e11d62adfed1824e3ed55c0d551d00281f4cdf7e8d20a233cdd2b67df66c5ddb56b1251f025fc7abf59ddb0f78c9c07

**Review by paulmultiversx — DISMISSED** [review]

**Pull request closed without merging**
