### PR TITLE
Token Branding

### PR DESCRIPTION
**Pull request by GuticaStefan**
Token Branding

### CODE REVIEW

**Comment by GuticaStefan** [comment]
{
  "address": "erd1m8tzqzs20gjswwctq6hk4kxrgsdzvcuns5yhw6ffx3x3fxpru3yqrjmds9",
  "message": "0x38643065393634393933656337383138353230383835393030643262616136373232313539623736",
  "signature": "0xd2972d130480f6960f423b8e134ef7e9c151ca572456c7c57dd624c87d71064b76a7f78d6773174f7c00caf11f5a8f44d4dae2c752a93c9607062325fb92fe0d",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by GuticaStefan** [comment]
{
  "address": "erd1m8tzqzs20gjswwctq6hk4kxrgsdzvcuns5yhw6ffx3x3fxpru3yqrjmds9",
  "message": "0x38643065393634393933656337383138353230383835393030643262616136373232313539623736",
  "signature": "0xd2972d130480f6960f423b8e134ef7e9c151ca572456c7c57dd624c87d71064b76a7f78d6773174f7c00caf11f5a8f44d4dae2c752a93c9607062325fb92fe0d",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by GuticaStefan** [comment]
{
  "address": "erd1m8tzqzs20gjswwctq6hk4kxrgsdzvcuns5yhw6ffx3x3fxpru3yqrjmds9",
  "message": "0x38643065393634393933656337383138353230383835393030643262616136373232313539623736",
  "signature": "0xd2972d130480f6960f423b8e134ef7e9c151ca572456c7c57dd624c87d71064b76a7f78d6773174f7c00caf11f5a8f44d4dae2c752a93c9607062325fb92fe0d",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by GuticaStefan** [comment]
{
"address": "erd1m8tzqzs20gjswwctq6hk4kxrgsdzvcuns5yhw6ffx3x3fxpru3yqrjmds9",
"message": "0x38643065393634393933656337383138353230383835393030643262616136373232313539623736",
"signature": "0xd2972d130480f6960f423b8e134ef7e9c151ca572456c7c57dd624c87d71064b76a7f78d6773174f7c00caf11f5a8f44d4dae2c752a93c9607062325fb92fe0d",
"version": 1,
"signer": "ErdJS"
}

**Review by dragos-rebegea — APPROVED** [review]

**Pull request merged**
