### PR TITLE
Add assets for contract erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqflllllsnczv3v

### PR DESCRIPTION
**Pull request by PhyByte**

### CODE REVIEW

**Comment by paulmultiversx** [comment]
Hi, @PhyByte 


We have a limitation at only 1 asset / PR so please split it in separate PRs.

Also, don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

**Comment by PhyByte** [comment]
{"address":"erd1tjygwhw5ylmv3v52ucvhmz0q7r0hafz4cfndjaskss5ahz28l3hqdvxqct","message":"0x37653763333636313464306336353663306330356366396466363534383538613835396266376437","signature":"0x0a437a1dd3169a81a21abc957aaa2b8b506f1faf0949408a3d10f2cf1fbc0bdac4427caf1fddb4323252fa9abd8ec568c50bce10ddb719db52fc75419c2b8803","version":1,"signer":"ErdJS"}

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hey, @PhyByte 

You have an Invalid dimensions for PNG! ( 513 x 513 )

logo.png (must have a resolution of 200x200 pixels) 
max logo size 100KB

**Comment by PhyByte** [comment]
{"address":"erd1tjygwhw5ylmv3v52ucvhmz0q7r0hafz4cfndjaskss5ahz28l3hqdvxqct","message":"0x34666130316433303533353361303137393161393935393363376135343861646430663537346131","signature":"0x664dd6c0a0f5128e4c3d9fd1a66aa5a38e5d3feff7907a920be5959d9ac7488ec09cfda88009082fa978e4fd5d736f813d3f3a359024de8542de28aa8db6b203","version":1,"signer":"ErdJS"}

**Review by paulmultiversx — APPROVED** [review]

**Comment by PhyByte** [comment]
Thanks for your fast reactions @paulmultiversx 

Have a great day!!!!

**Pull request merged**
