### PR TITLE
Add assets for 'CARS-d90e27'

### PR DESCRIPTION
**Pull request by solid38**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Review by paulmultiversx — CHANGES_REQUESTED** [review]
Hi, @solid38 

Please provide a signature for the latest commit sha: `717d9092445b4ca29e098d7d562ab6adaad6044f` which must be signed with the owner wallet address: 
`erd1jgzw6hrt48jhus0ntp4egmltrcdg8qu7spmultaqxxmx96fq09mslgtsqq`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

**Comment by solid38** [comment]
It's good ;)
{
  "address": "erd1jgzw6hrt48jhus0ntp4egmltrcdg8qu7spmultaqxxmx96fq09mslgtsqq",
  "message": "0x37313764393039323434356234636132396530393864376435363261623661646161643630343466",
  "signature": "0xf6898159e2ee13c402d382efd376285d5657db7f5bbfd8b968459a880616c37dfbf5a2967bedb19dbbcdea322a86100d7d9ba94aa1b9ca67d84acc2c0ab04e03",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @solid38.

Please paste only the signature in a new comment:
 '0xf6898159e2ee13c402d382efd376285d5657db7f5bbfd8b968459a880616c37dfbf5a2967bedb19dbbcdea322a86100d7d9ba94aa1b9ca67d84acc2c0ab04e03'

**Comment by solid38** [comment]
> Hi, @solid38.
> 
> Please paste only the signature in a new comment: '0xf6898159e2ee13c402d382efd376285d5657db7f5bbfd8b968459a880616c37dfbf5a2967bedb19dbbcdea322a86100d7d9ba94aa1b9ca67d84acc2c0ab04e03'

Corrected ;)

**Comment by solid38** [comment]
0xf6898159e2ee13c402d382efd376285d5657db7f5bbfd8b968459a880616c37dfbf5a2967bedb19dbbcdea322a86100d7d9ba94aa1b9ca67d84acc2c0ab04e03

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Are you sure you signed it using the owner address wallet? 

Please make sure you provide a signature for the latest commit sha: `717d9092445b4ca29e098d7d562ab6adaad6044f` which must be signed with the owner wallet address: 
`erd1jgzw6hrt48jhus0ntp4egmltrcdg8qu7spmultaqxxmx96fq09mslgtsqq`

**Comment by solid38** [comment]
0xf6898159e2ee13c402d382efd376285d5657db7f5bbfd8b968459a880616c37dfbf5a2967bedb19dbbcdea322a86100d7d9ba94aa1b9ca67d84acc2c0ab04e03

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
We're making some checks on the process and will revert back with an update. Thanks for your patience in the meantime.

**Pull request merged**
