### PR TITLE
Add assets for 'KWAK-3490c4'

### PR DESCRIPTION
**Pull request by 48zp**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @48zp 

We have a limitation at only 1 asset / PR so please split it in separate PRs.

Also, don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/

Thanks a lot!

**Comment by 48zp** [comment]
Hi @paulmultiversx 

I've used https://assets.multiversx.com/ and signed my last commit but the automatic PR mixed it with older commits

Do you need me to sign again?

**Comment by 48zp** [comment]
Anyway, here it is:

{
  "address": "erd1pws6zyhwv7t8dut0rkkvxgqatt5dzag4ghdlkqxm3jjutwaytuqque48zp",
  "message": "0x32386262383833386136306334646665336434633739346537303132663232613966376133346238",
  "signature": "0x98b95549f3bd8400ef5e978af6e810e0452961fe4fbf0f7936b094af120a7972392336ba79f5892ceb93b132c5c10be17b749d397ec2986d5960a9a24dfffe0f",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by paulmultiversx** [comment]
You need to create a PR for each asset. Create 1 PR for the token and create 1 PR for the account and paste the signature for each of them.

**Pull request closed without merging**
