### PR TITLE
Add assets for contract erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqz0llllsup4dew

### PR DESCRIPTION
**Pull request by RdtBui**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @RdtBui 

Please provide a signature for the latest commit sha: `0f0cf3063a8dab62705fbb5802719953f94c9886` which must be signed with the owner wallet address: 
`erd15tf9yjtf7aznx46tcs6z9cdqdypm6hzgh2utjme9mksz4cpk6m2qhe874f`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by RdtBui** [comment]
0xa601283d00efeb14bb45ba232f3a175ef181ac985abe1b6e505c685190fedb44b3698decd7145c479c80a541f988831b7e1c3effcc4b5f125ff9e53df5fbf407

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @RdtBui 

It appears the signature is not correct.

Please provide a signature for the latest commit sha: `2b4d5c1bc3681ecd4e18286bba76219e75edf80d` which must be signed with the owner wallet address: 
`erd15tf9yjtf7aznx46tcs6z9cdqdypm6hzgh2utjme9mksz4cpk6m2qhe874f`

Thanks

**Comment by RdtBui** [comment]
Signed `2b4d5c1bc3681ecd4e18286bba76219e75edf80d`:
```
{"address":"erd15tf9yjtf7aznx46tcs6z9cdqdypm6hzgh2utjme9mksz4cpk6m2qhe874f","message":"0x32623464356331626333363831656364346531383238366262613736323139653735656466383064","signature":"0xd84fd6fb991a0e2b890b23c320897dd3426445e65b80a831297213233203e189410ddee7221eac13068f7699416bded2e39351e91968509f15f17a74f2687005","version":1,"signer":"ErdJS"}
```

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
