### PR TITLE
Added branding for the token PRMS-6423d4

### PR DESCRIPTION
**Pull request by stemolti**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @stemolti 

You have an Invalid dimensions for PNG: 202 x 202

logo.png (must have a resolution of 200x200 pixels)

Please fix it before we can proceed with the merging of this PR. 

---

Please provide a signature for the latest commit sha: `1f727aeb76245ea5f53bba94636f21412a4679cf` which must be signed with the owner wallet address: 
`erd1cq0h7snfdxr8xdra2tj506l3t59ru87x44kgy2zgkykf87wn5teqggfdwq`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature here in a comment: https://utils.multiversx.com/

Step-by-step guide:

Step 1: Copy latest commit sha
Step 2: Open: https://utils.multiversx.com/
Step 3: Log in with your owner address wallet
Step 4: Click the 'Sign Message' feature
Step 5: Paste the commit sha in the first column and hit sign
Step 6: Copy-paste the provided output signature here in a new comment

Thanks.

**Comment by stemolti** [comment]
{
  "message": "61663962306165646336616433653936313965363333313433656135643763663064616635383364",
  "signature": "079fd5deb4550129d88d8c42208040c19c7cbd077112a74cf16b8ebca7cd68718f0a69bfd0b796d63e261a94ded58b28e1c5f87c0ff3f507fdbe1a998477bc02",
  "address": "erd1cq0h7snfdxr8xdra2tj506l3t59ru87x44kgy2zgkykf87wn5teqggfdwq",
  "version": 1,
  "signer": "wallet-connect-v2"
}

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
@stemolti 

Invalid dimensions for PNG! ( 198 x 198 )

Please re-upload it at exactly 200x200.

**Comment by paulmultiversx** [comment]
@stemolti 

logo.SVG is not a square: w:513 h:514

Requirements:
logo.svg (must be in a square format) 
logo.png (must have a resolution of 200x200 pixels) 
max logo size 100KB

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
@stemolti 

Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again:
https://jsonlint.com/

Thanks

**Review by stemolti — COMMENTED** [review]
Thank you for your patience!

**Comment by stemolti** [comment]
Honestly I don't know what is happening. I did what you told me @paulmultiversx

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
