### PR TITLE
Add assets for 'DQA-f8dcc9'

### PR DESCRIPTION
**Pull request by Raul-DQA**

### CODE REVIEW

**Comment by Raul-DQA** [comment]
072d29de963a7db3b2f6017eff8ea37d786dbc9a041b1c7386bb901069f2b0643fc98dd63a5d1c38f76a8be50629363fcb8f2f9a04112faa0371294bc04f1f06
https://utils.multiversx.com/sign-message?signature=072d29de963a7db3b2f6017eff8ea37d786dbc9a041b1c7386bb901069f2b0643fc98dd63a5d1c38f76a8be50629363fcb8f2f9a04112faa0371294bc04f1f06&message=45cf2b0789848bef5a0db3fe27a501c433a0e610&address=erd1n5fxpsykzrjuxqv0znhkayph6mp5azsmurtvs8e0vwhu794jgd4qr50fa2

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Raul-DQA 

It seems the SVG not a perfect square. It is 150 x 149. Can you please re-upload it properly once again?

Thanks

**Comment by Raul-DQA** [comment]
> Hi, @Raul-DQA
> 
> It seems the SVG not a perfect square. It is 150 x 149. Can you please re-upload it properly once again?
> 
> Thanks

How can I do that ? Can't figure it out.

**Comment by Raul-DQA** [comment]
> > Hi, @Raul-DQA
> > It seems the SVG not a perfect square. It is 150 x 149. Can you please re-upload it properly once again?
> > Thanks
> 
> How can I do that ? Can't figure it out.

Also, how cannot be a perfect square, it is a 200X200 pixels as required

**Comment by Raul-DQA** [comment]
let's do it again. Must be a glitch

**Comment by Raul-DQA** [comment]
> let's do it again. Must be a glitch

@paulmultiversx - do I have to restart the process ?? or can I change it here?

**Comment by Raul-DQA** [comment]
> > let's do it again. Must be a glitch
> 
> @paulmultiversx - do I have to restart the process ?? or can I change it here?

I have reuploaded

**Comment by paulmultiversx** [comment]
@Raul-DQA it seems it is deleted now as you have only 2 files: json.info and logo.png

**Comment by Raul-DQA** [comment]
> @Raul-DQA it seems it is deleted now as you have only 2 files: json.info and logo.png

@paulmultiversx - yes I deleted and tried to re-upload here but don't know how. So, I pulled a different request

**Comment by Raul-DQA** [comment]
> > @Raul-DQA it seems it is deleted now as you have only 2 files: json.info and logo.png
> 
> @paulmultiversx - yes I deleted and tried to re-upload here but don't know how. So, I pulled a different request

@paulmultiversx  - should I start the whole process again ? I think I found the Flaw and fixed it just now.

**Comment by Raul-DQA** [comment]
@paulmultiversx , I saw that the 2nd Pull isn't successful again. let me pull again, I think I have fixed the issue

**Pull request closed without merging**
