### PR TITLE
Add assets for 'GGLD-f8465b'

### PR DESCRIPTION
**Pull request by MantorMBU**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @MantorMBU 

Please provide a signature for the latest commit sha: `4f3cda00a0c322e9137156361f65246e7bdf83ef` which must be signed with the owner wallet address: 
`erd1x39tzlh6ssqtsdnyhxvdj2jvgwvpxvczk7933shvhc6s6fl7m2ys8kwalt`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by MantorMBU** [comment]
{
  "address": "erd1x39tzlh6ssqtsdnyhxvdj2jvgwvpxvczk7933shvhc6s6fl7m2ys8kwalt",
  "message": "0x65726431783339747a6c68367373717473646e79687876646a326a76677776707876637a6b373933337368766863367336666c376d327973386b77616c74",
  "signature": "0xd783bf663cd69170a559d28275bcdef378f50089e15d95c437e27928f6473609685076a061c098cadec12f04e6ba96eec12126012201382ee5a3871fc56baa0e",
  "version": 1,
  "signer": "ErdJS"

}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @MantorMBU 

You need to sign this line '4f3cda00a0c322e9137156361f65246e7bdf83ef' and paste the signature in a new comment.

**Comment by MantorMBU** [comment]
{
  "address": "erd1x39tzlh6ssqtsdnyhxvdj2jvgwvpxvczk7933shvhc6s6fl7m2ys8kwalt",
  "message": "0x34663363646130306130633332326539313337313536333631663635323436653762646638336566",
  "signature": "0xc5107f7e86c76ea99733248e6bb4c642adafd8eeee28e38d91d875ee56f9e397c14d3bd8647b4b986f30b983ed336db25d0adcf72ccb0575d173e750c42f2a0f",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by MantorMBU** [comment]
{
  "address": "erd1x39tzlh6ssqtsdnyhxvdj2jvgwvpxvczk7933shvhc6s6fl7m2ys8kwalt",
  "message": "0x34663363646130306130633332326539313337313536333631663635323436653762646638336566",
  "signature": "0xc5107f7e86c76ea99733248e6bb4c642adafd8eeee28e38d91d875ee56f9e397c14d3bd8647b4b986f30b983ed336db25d0adcf72ccb0575d173e750c42f2a0f",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
