### PR TITLE
Create erd1qqqqqqqqqqqqqpgqyqw03h2nf5s43xj6qzjzknwt9zfh88gglzmsk32wn0

### PR DESCRIPTION
**Pull request by EdiMarian**

### CODE REVIEW

**Review by tdumitrache — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hey @EdiMarian.  Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Comment by EdiMarian** [comment]
Ops:))

**Comment by cfaur09** [comment]
Hi, instead of
```
 "tags": [
    "muf",
    "game",
    "1v1"
  ]
```
  
  please update with:
```
   "tags": [
    "multifights",
    "token",
    "distribution"
  ]
```

**Comment by EdiMarian** [comment]
I changed it, thanks.

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
