### PR TITLE
Add assets for 'TADA-1e4ac8'

### PR DESCRIPTION
**Pull request by AT-Vivoka**

### CODE REVIEW

**Comment by AT-Vivoka** [comment]
7d66cdf318191b8c3dd34bf00e2fcea0ae6095df1ad20a8cbede2895bf91526f5ea769f03bd3b03f3fbb682a84364eb2cd082ebe6076ea9bb9abff51df39600d
https://utils.multiversx.com/sign-message?signature=7d66cdf318191b8c3dd34bf00e2fcea0ae6095df1ad20a8cbede2895bf91526f5ea769f03bd3b03f3fbb682a84364eb2cd082ebe6076ea9bb9abff51df39600d&message=2cb6de24c356194358878e52582b59e999c6b83a&address=erd1ydsg2m9tg3sygwdk8p5q5jd537acdmq28jrweyn7jr2mvtmnd29qhkzhxc

**Comment by AT-Vivoka** [comment]
Hi
Can you merge my request, I want to change the info and logo of the token 
Thank in advance

**Comment by paulmultiversx** [comment]
Hey, @AT-Vivoka.

Unfortunately we can not merge this PR with active conflicts in it. You must first fix the conflicting files: 

devnet/tokens/TADA-1e4ac8/info.json
devnet/tokens/TADA-1e4ac8/logo.png
devnet/tokens/TADA-1e4ac8/logo.svg

You can use the Assets dApps for this: https://assets.multiversx.com/

Thanks!

**Comment by AT-Vivoka** [comment]
I just want to update the logo 
And I already did this from https://assets.multiversx.com/

I don't kwon how to do 

Thank in advance

**Pull request closed without merging**
