### PR TITLE
Valoro: Fees Distributor

### PR DESCRIPTION
**Pull request by k05ta5**

### CODE REVIEW

**Comment by k05ta5** [comment]
{
  "address": "erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel",
  "message": "0x65726431717171717171717171717171717067716b636c6c71326d67726e7368686635343365736536677777337932666a67733675377a736d7133346b36",
  "signature": "0x8e2a01106ffe534b74d9dd5c69d4f153424abdb529df8ed8807238856e0167c22e8f3f7ebe1ccd6346108ea3a4fd5f1cb689277315e336f25e3cb9dd02534f02",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @k05ta5 

It seems the signature is not valid. 

Please provide a signature for the latest commit sha: `d1eacacf6567caa5a10b8d87c4fc100267bc3afb` which must be signed with the owner wallet address: 
`erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel`

Thanks

**Comment by k05ta5** [comment]
Hi  @paulmultiversx ,

This one should be valid.

Thanks!

**Comment by k05ta5** [comment]
{
  "address": "erd1lnmfa5p9j6qy40kjtrf0wfq6cl056car6hyvrq5uxdcalc2gu7zsrwalel",
  "message": "0x64316561636163663635363763616135613130623864383763346663313030323637626333616662",
  "signature": "0x85d8abab3b5c7d3e48677ff11870f913c5e0595611cd6282bf6bf5346bb0247bbb02270a7fb79c19f8806f287f95dfee577640905fcfe0fe4427a53a9347f402",
  "version": 1,
  "signer": "ErdJS"
}

**Pull request merged**
