### PR TITLE
FLIPY-a358d4

### PR DESCRIPTION
**Pull request by grenderro**
Hi

New meme token powered by ArtCPAclub.
Thank you for your time

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @grenderro 

Please provide a signature for the latest commit sha: `4951e3f79af98ae377894fc4cc2b34501172bace` which must be signed with the owner wallet address: 
`erd1hnqgq9zzngmn2can9pzftydcpggsrrlhf67dux073pqsqt7u8gaql00s7j`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by grenderro** [comment]
{
  "address": "erd1hnqgq9zzngmn2can9pzftydcpggsrrlhf67dux073pqsqt7u8gaql00s7j",
  "message": "0x34393531653366373961663938616533373738393466633463633262333435303131373262616365",
  "signature": "0xb7a8ad31bc34f4e346b4de7886fd2f4ea7d725ba5d9a5a0acc91919360a2f4513664ddbe041755db0aa637138822da481b6496191cb393ed84474db37ec4610d",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by grenderro** [comment]
Json file corrected.

**Review by paulmultiversx — APPROVED** [review]

**Comment by grenderro** [comment]
Json issue identified and corrected

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
