### PR TITLE
Add assets for 'MEMEX-3e6636'

### PR DESCRIPTION
**Pull request by MeMeXCoin**

### CODE REVIEW

**Comment by MeMeXCoin** [comment]
> Hi, @MeMeXCoin
> 
> Your logos are too large.
> 
> logo must have a resolution of 200x200 pixels max logo size 100KB
> 
> Please re-uploade them properly.
> 
> Also, don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.
> 
> Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment for each PR: https://utils.multiversx.com/
> 
> Thanks a lot!

Hello
Where can I find instructions on how to do a signature please?

**Comment by MeMeXCoin** [comment]
{
  "address": "erd1mhd74cgcyhc27ng562c74tzs4zg8e0sqj9fu6acafjga8p2at3wq7suwca",
  "message": "0x4164642061737365747320666f72204d454d45582d336536363336",
  "signature": "0x78096955f40f741e6f08db9dafe2f1e1a1ba429bb9e7ae302ba2093066b7bc1666666538af99dc9e50d6feb3e668da24417bc440639e462546426ee3c1d3590e",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by MeMeXCoin** [comment]
Hi @paulmultiversx 
I have made the requested changes

Thank you

**Comment by paulmultiversx** [comment]
Your files names are invalid. Please create a fresh & correct PR using Assets dApp.

Prepare the relevant token files:

info.json
logo.svg (must be in a square format)
logo.png (must have a resolution of 200x200 pixels)  
max size 100KB

You can use the Assets dApp for this: https://assets.multiversx.com/

Thanks.

**Pull request closed without merging**
