### PR TITLE
Add Branding for multiple wallets within Ofero Network

### PR DESCRIPTION
**Pull request by oferonetwork**
Adding logo and wallet information for ASH Ventures, an Ofero Network partner

{"address":"erd1qw0zjyghzvazdm7sh4yg4hfuk42xy0yyt4vspdmwwye6ektpd2as7gfe3j","message":"0x31323038383665356362626431343335383761616563323237653531636366646462623539613832","signature":"0x48ac24afd60f2e12ece53346ced51b3c0d3f4cab7fc6a21923edf4127a181765f0fdcb35cb2dbab0f4a099ea43ad04e2d7a22c254ee222e552beccf31571e502","version":1,"signer":"ErdJS"}

### CODE REVIEW

**Comment by oferonetwork** [comment]
For hatOFF Venture

{"address":"erd1rmykkv0ttkdm6m9e6f8p3yel9vxcu2xlnxvm0jeyykxmdfjj9nhsps098q","message":"0x35643432396236663162623764386634393538376466373331383831333765363166373339343532","signature":"0x2034c8910f85715f4f03a9d6352189908df9532f8abaea80104c39e76082382e741031200b51c468cac47dccfd36ef1e5b475de17a054d82c3b32d263f07970d","version":1,"signer":"ErdJS"}

**Review by oferonetwork — COMMENTED** [review]
{"address":"erd10f0hq3df0ttssy0a250s4uhqtg75p22gen99tdmgtmsnj98udzvsw0lref","message":"0x33633931396337663062313466356333643632313232346264366266666432373936616238376665","signature":"0xcc95290e71c6f06e4b0e89f99227d3b2059f85fb200a02ce99d0843d837fb3370e9d531b39e19cac502e6fd660e4a22977a45d192dba332c0425283ce5306b07","version":1,"signer":"ErdJS"}

**Review by oferonetwork — COMMENTED** [review]
{"address":"erd1zwx7vmd6ycs94nrvy6wmaz58qpahau8q5zz82tvac0msf36rvmds95xnex","message":"0x38333032613062313466653534323661663762663330306161376230633866346435366637653239","signature":"0x2c47cfe3a4175dc2c348275d8279b9577ae779fef9dd85fda57fa5b2880db9fd13fca7c00d12e09067b86a35c8ec45a400d852ac41715a3004a324b6a553de00","version":1,"signer":"ErdJS"}

**Comment by paulmultiversx** [comment]
Hi, @oferonetwork.

We have a limitation at only 1 asset / PR so you will need to create separate PRs for each account. 

Don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address for each PR. The (0x...) signature, not the entire output from Utils dApp.

Thanks!

**Pull request closed without merging**
