### PR TITLE
Staking4All Staking Provider ID

### PR DESCRIPTION
**Pull request by staking4all**
Hi

Please accept

Thanks

### CODE REVIEW

**Comment by staking4all** [comment]
0x0634a06e6dcd24d0503be24e0d4ccde0a5947b6ed31e697d8f5be1ac33743645d99cfd100daa5d2e23d1bd9d21d0c0e23cbd4f242bd13d1afb1c87b267399805

**Comment by staking4all** [comment]
0x359ff48d1e963df9e4212737b71613f0e54772dfa75c81de120c8cd64508fcf3e0f401d94cf342f3c966ffce5b34c0fc0c90c38fda6a7098d65a04ceaf88d205

**Comment by staking4all** [comment]
0xa864e4b267a747362b1d405c32ff9cc91fd32d6fbf333cfdca6688334611f5f08ed903ae2c6b670c14e65717931cb0e55e55e004e6f5271a7d9999afd1b3d10d

**Comment by staking4all** [comment]
0xa864e4b267a747362b1d405c32ff9cc91fd32d6fbf333cfdca6688334611f5f08ed903ae2c6b670c14e65717931cb0e55e55e004e6f5271a7d9999afd1b3d10d

**Comment by staking4all** [comment]
0x0fe683944cf493d9e4b84acc056b4cc008f9bf8b6c31ef9b8d9b78d25496ffe4a941aa8de5728c6ecfff04311cc41143468afdc7477a261a681c0f9c5071fa09

**Review by iulianpascalau — APPROVED** [review]

**Pull request merged**
