### PR TITLE
Fixed typo EGLDSqueeze

### PR DESCRIPTION
**Pull request by egldsqueeze**
Fixed typo EGLDSqueeze

### CODE REVIEW

**Comment by egldsqueeze** [comment]
{"message":"0x63393433333664323063333565643937383831323935653838653961386166323265303133383138","signature":"0x2fa26f0681896ff53808ad5d27f8c276d904d7b6230c290509d672ae0fbcf76d4cd8f07260ecfeee11150495b0fa09176c5c0ca89a2dd59f760ef8d7f89df004","address":"erd1naw2nke0rcx54r58rqa8hy2hv34vjukw2vsjuvy29ad7yl9rjalsrdkgq3","version":1,"signer":"sdk-js"}

**Comment by egldsqueeze** [comment]
Hi, how long does it usually take for a change to show up here in explorer? - https://explorer.multiversx.com/identities/egldsqueeze

**Comment by paulmultiversx** [comment]
Hey, @egldsqueeze usually around ~minutes or so ;)

**Comment by egldsqueeze** [comment]
Thanks. It already worked for while. Currently, I can see no "bradning" here, can you help me please? 

https://explorer.multiversx.com/providers/erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqpvllllls3lkx6d

**Comment by paulmultiversx** [comment]
@egldsqueeze it appears you need to have at least 1 node (add 1250EGLD) in order to be reflected on the Explorer.

**Comment by egldsqueeze** [comment]
Make sense, works now. Sorry for bothering. Appreciate it! #EGLDSqueeze

**Pull request merged**
