### PR TITLE
Add assets for 'MEMEX-3e6636'

### PR DESCRIPTION
**Pull request by MeMeXCoin**

### CODE REVIEW

**Comment by MeMeXCoin** [comment]
8621229feb0e004001ee0a9d3c87ed17c1e4d591f1d1e8bec52b69152ee8fe42142c6d4e3a93efee3352c65c5e0462c32eb8a44bd962c0f45711ff039b9fff0e
https://utils.multiversx.com/sign-message?signature=8621229feb0e004001ee0a9d3c87ed17c1e4d591f1d1e8bec52b69152ee8fe42142c6d4e3a93efee3352c65c5e0462c32eb8a44bd962c0f45711ff039b9fff0e&message=14143e8ec0b5a915f62d0c15095be836cfed0919&address=erd1mhd74cgcyhc27ng562c74tzs4zg8e0sqj9fu6acafjga8p2at3wq7suwca

**Comment by MeMeXCoin** [comment]
[info.json](https://github.com/multiversx/mx-assets/files/14817316/info.json)

**Comment by MeMeXCoin** [comment]
Using the Assets dApp to create a new PR on https://assets.multiversx.com/  , doesnt allow me to add the info file. Please find it attached here

[info.json](https://github.com/multiversx/mx-assets/files/14817318/info.json)

**Comment by paulmultiversx** [comment]
Hi, @MeMeXCoin 

Your PR must have exactly 3 files and all the files need to be added in the Tokens directory:

info.json ([https://docs.multiversx.com/tokens/esdt-tokens)
logo.svg (must be in a square format) 
logo.png (must have a resolution of 200x200 pixels) 
max logo size 100KB

Please use the Assets dApp to create a new PR: https://assets.multiversx.com/

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Pull request closed without merging**
