### PR TITLE
Add assets for BRKZ-ff08dc

### PR DESCRIPTION
**Pull request by n0xNFT**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @n0xNFT.

Please provide a signature for the latest commit sha: `b4e4aa01ef04699e80bfb6c4ee778962b20e82bb` which must be signed with the owner wallet address: 
`erd1p4gzmyha0qve47calgegujaa76nmregxldhq4s8rkt4t2wegwkpsn9vavu`

Feel free to use the Sign Message feature from the Utils dApp: https://utils.multiversx.com/

Thanks.

**Comment by n0xNFT** [comment]
hi @paulmultiversx ,

the message has been signed, please see attached screenshot.
cbeb762a-ecbd-4a88-9865-e01225663eae

thanks,
n0x

**Comment by n0xNFT** [comment]
{"address":"erd1p4gzmyha0qve47calgegujaa76nmregxldhq4s8rkt4t2wegwkpsn9vavu","message":"0x62346534616130316566303436393965383062666236633465653737383936326232306538326262","signature":"0x8ab64881698f6fb344a32b37991f699bcf7c2627c3cb1b044acfc06667adb976e0cffa69d297435ef23bcb70027d1873b53bd0a8852788a2ea0c6cbe3b73fa0f","version":1,"signer":"ErdJS"}

**Comment by n0xNFT** [comment]
@paulmultiversx please check now.

thanks,
n0x

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
