### PR TITLE
Add assets for 'STMM-a23813'

### PR DESCRIPTION
**Pull request by Catal1n86**

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Catal1n86 

Please provide a signature for the latest commit sha: `920c0456dcf83b6c88f8fe960eec2c7c621990e5` which must be signed with the owner wallet address: 
`erd1sjdwa82z54q4h7jhwydm0lyq5m3w8vwm7qdk4fpv4a5zj2qeqlnqu375v6`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by Catal1n86** [comment]
{
  "address": "erd1sjdwa82z54q4h7jhwydm0lyq5m3w8vwm7qdk4fpv4a5zj2qeqlnqu375v6",
  "message": "0x393230633034353664636638336236633838663866653936306565633263376336323139393065",
  "signature": "0x2194edfe4f7fb296e7d0f047cbf4558bf4a1f9e231424d34e183c10a4f7d782967ff01555d596c1a456437d0088789c843de1b6c60da27a87d069bd5d9062104",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Catal1n86 

The signature provided is not correct. 

Please provide a signature for the latest commit sha: '920c0456dcf83b6c88f8fe960eec2c7c621990e5' which must be signed with the owner wallet address:
'erd1sjdwa82z54q4h7jhwydm0lyq5m3w8vwm7qdk4fpv4a5zj2qeqlnqu375v6'

**Comment by Catal1n86** [comment]
{
  "address": "erd1sjdwa82z54q4h7jhwydm0lyq5m3w8vwm7qdk4fpv4a5zj2qeqlnqu375v6",
  "message": "0x39323063303435366463663833623663383866386665393630656563326337633632313939306535",
  "signature": "0x2ef498c28e420fc34cc4e1c65b9f00419704afac69bdeefa1494949c259d3978e549ecdd142c0764e80e81fc42f48081e8164350d1843b341e5a76685ca38109",
  "version": 1,
  "signer": "ErdJS"
}

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
