### PR TITLE
Updates to identities

### PR DESCRIPTION
**Pull request by tanghel**

### CODE REVIEW

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Comment by tanghel** [comment]
Only one identity must be edited at a time

**Review by cfaur09 — APPROVED** [review]

**Comment by tanghel** [comment]
0xb277540258cc403b96f00d6e5516496c76776bf3727b5a1a9883950be1b90a0eb0161a49ab1293d93b2484746ca772f054276e65a890fa1e94a150fe55a8ee05

**Comment by tanghel** [comment]
1b0054afc30af8c3d4ed016ed2d7e9c7ed1fa109f04d9119f55a09e5367d0787d3018ab753d29687efb5ee85ed709b6b3a0d5c321d911711cf44ae3563f78d06

**Review by cfaur09 — APPROVED** [review]

**Pull request merged**
