### PR TITLE
Add assets for 'BAMBOO-2892cb'

### PR DESCRIPTION
**Pull request by xPandiMVX**

### CODE REVIEW

**Comment by xPandiMVX** [comment]
bamboo2

**Comment by xPandiMVX** [comment]
Hi. Signature OK.

0xc3e3e232d12262df840721e95d2e29699e8fd14764022ee248ce4771dfffbba6c0df56a210cc0d7f32f73e5584e487728a51cede97d977a0f6b5b33850c86801

**Comment by paulmultiversx** [comment]
Hi, @xPandiMVX 

You need to replace your logo.svg from Tokens directory, not here in a comment. 

Thanks

**Comment by xPandiMVX** [comment]
Sorry.
Now it's ok. 
I need to sign again ?

**Review by paulmultiversx — APPROVED** [review]

**Pull request merged**
