### PR TITLE
Update info.json

### PR DESCRIPTION
**Pull request by hlnagy**
Updated websites.

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @hlnagy 

Your json has an issue. Please validate it with a dedicated tool like this one, before you upload it again:
https://jsonformatter.curiousconcept.com/
https://jsonlint.com/

Feel free to use the Sign Message feature from the Utils dApp and paste the signature here in a comment: https://utils.multiversx.com/

Also, don't forget to paste in a comment the signature for the latest commit sha which must be signed with the owner wallet address.

Step-by-step guide:

Step 1: Copy latest commit sha
Step 2: Open: https://utils.multiversx.com/
Step 3: Log in with your owner address wallet
Step 4: Click the 'Sign Message' feature
Step 5: Paste the commit sha in the first column and hit sign
Step 6: Copy-paste the provided output signature here in a new comment

Thanks.

**Comment by hlnagy** [comment]
{
  "message": "7b20202020202277656273697465223a202268747470733a2f2f6d7678666f6f7462616c6c2e776978736974652e636f6d2f776562736974652f656e222c2020202020226465736372697074696f6e223a20225468652045464f4f20746f6b656e206973206173736f63696174656420776974682074686520e29abd45466f6f7462616c6c2d582070726f6a6563742c20616c6c6f77696e6720757365727320746f20706172746963697061746520696e207468652070726f6a65637420616e6420636f6e7472696275746520746f2074686520636f6d6d756e697479277320646576656c6f706d656e742e222c202020202022736f6369616c223a207b20202020202020202022656d61696c223a2022656c726f6e64666f6f7462616c6c6e66747340676d61696c2e636f6d222c20202020202020202022626c6f67223a202268747470733a2f2f6d656469756d2e636f6d2f40656c726f6e64666f6f7462616c6c222c2020202020202020202258223a202268747470733a2f2f782e636f6d2f45466f6f7462616c6c5f58222c2020202020202020202277686974657061706572223a202268747470733a2f2f6d656469756d2e636f6d2f40656c726f6e64666f6f7462616c6c2f656c726f6e642d666f6f7462616c6c2d70726f6a656374732d776869746570617065722d353138343039336164623230222c2020202020202020202274656c656772616d223a202268747470733a2f2f742e6d652f656c726f6e64666f6f7462616c6c2220202020207d2c2020202020226c6f636b65644163636f756e7473223a207b20202020202020202022657264316739637661356d72677636393865687563356467676b6e3874756461376a786d7a30377a666c6a727632307335383070723067736d366a653376223a20225465616d20616e642054726561737572792076657374696e67222c20202020202020202022657264316b3877377935667467327561783876386e67387035617a6a7739367a7a66676b79397633667964747065327877647a303030377133686c397a38223a20224c697175696469747920526573657276652057616c6c6574222c20202020202020202022657264317171717171717171717171717170677178716e6170326439306630736a3076333461306475617171373878337132707233716d71396761646734223a20225465616d20616e64205472656173757279204269744c6f636b2220202020207d2c202020202022737461747573223a202261637469766522207d",
  "signature": "411d726011949d4bf1c92cadf18cc082637ad54b9d34f0f8c08b363d955ccf883ac53a656777c3de49d9f74bea1693cdc0e3aab09d88709a1d871d50a9f0460a",
  "address": "erd1p5hfnx87q4pddwsyz23e5pqv8550rsfat902j6g4ckdh070055hshct4my",
  "version": 1,
  "signer": "extension"
}

**Review by paulmultiversx — DISMISSED** [review]

**Comment by paulmultiversx** [comment]
@hlnagy it seems you still have an invalid json. Did you validated the json using one of the suggested tools?

**Comment by hlnagy** [comment]
{
  "message": "7b202020202277656273697465223a2268747470733a2f2f6d7678666f6f7462616c6c2e776978736974652e636f6d2f776562736974652f656e222c20202020226465736372697074696f6e223a225468652045464f4f20746f6b656e206973206173736f63696174656420776974682074686520e29abd45466f6f7462616c6c2d582070726f6a6563742c20616c6c6f77696e6720757365727320746f20706172746963697061746520696e207468652070726f6a65637420616e6420636f6e7472696275746520746f2074686520636f6d6d756e697479277320646576656c6f706d656e742e222c2020202022736f6369616c223a7b2020202020202022656d61696c223a22656c726f6e64666f6f7462616c6c6e66747340676d61696c2e636f6d222c2020202020202022626c6f67223a2268747470733a2f2f6d656469756d2e636f6d2f40656c726f6e64666f6f7462616c6c222c202020202020202258223a2268747470733a2f2f782e636f6d2f45466f6f7462616c6c5f58222c202020202020202277686974657061706572223a2268747470733a2f2f6d656469756d2e636f6d2f40656c726f6e64666f6f7462616c6c2f656c726f6e642d666f6f7462616c6c2d70726f6a656374732d776869746570617065722d353138343039336164623230222c202020202020202274656c656772616d223a2268747470733a2f2f742e6d652f656c726f6e64666f6f7462616c6c22202020207d2c20202020226c6f636b65644163636f756e7473223a7b2020202020202022657264316739637661356d72677636393865687563356467676b6e3874756461376a786d7a30377a666c6a727632307335383070723067736d366a653376223a225465616d20616e642054726561737572792076657374696e67222c2020202020202022657264316b3877377935667467327561783876386e67387035617a6a7739367a7a66676b79397633667964747065327877647a303030377133686c397a38223a224c697175696469747920526573657276652057616c6c6574222c2020202020202022657264317171717171717171717171717170677178716e6170326439306630736a3076333461306475617171373878337132707233716d71396761646734223a225465616d20616e64205472656173757279204269744c6f636b22202020207d2c2020202022737461747573223a2261637469766522207d",
  "signature": "54bbec39ae127d520b8c3eb5ec297a4782f9ff701d82f44d4ba953568fb6515aca62bd06e4cc6d2e0fcad3470932f9b1dea53f2fc27613a00a51b3545292fe03",
  "address": "erd1p5hfnx87q4pddwsyz23e5pqv8550rsfat902j6g4ckdh070055hshct4my",
  "version": 1,
  "signer": "extension"
}

**Comment by hlnagy** [comment]
Sorry again,
I hope it will be ok.

Have a nice day!

**Comment by hlnagy** [comment]
{
  "message": "31316162643166383837396134343638343332616663613661623564646561333135343865666361",
  "signature": "bbcf95c8ffe9eb5a52988c1cbc22645f43dab9e902c0912a7939daa6d2a5c14553319dc1d251186e00297697b43c70c2766794b6cbb9e158e2fd71093d79c804",
  "address": "erd1p5hfnx87q4pddwsyz23e5pqv8550rsfat902j6g4ckdh070055hshct4my",
  "version": 1,
  "signer": "extension"
}

**Comment by hlnagy** [comment]
Unfortunately, I just found the SHA now. It was also in the error feedback. I don't know where to find it otherwise.
Sorry, sorry, sorry.
And a big THANK.

**Comment by paulmultiversx** [comment]
All good. Have a lovely day!

**Pull request merged**
