### PR TITLE
Emorya Bridge SC

### PR DESCRIPTION
**Pull request by Toderean**
{
  "address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
  "message": "0x35333666663033666564663063306663303235303766313533623562653962633033626536373762",
  "signature": "0x42772d7a200a1ce7d772af20d1ab7e1fcaa18b423bbd7db6b902e610db47c8915517e976b06005f5f98aa46f87f923b71bb2485a1f1cde02bc9d609c9fffbc0b",
  "version": 1,
  "signer": "ErdJS"
}

### CODE REVIEW

**Review by paulmultiversx — APPROVED** [review]

**Comment by paulmultiversx** [comment]
Hi, @Toderean 

Please provide a signature for the latest commit sha: `9dd5715ae9a595843702d2e1ebcfe22cea668d8a` which must be signed with the owner wallet address: 
`erd1cdxt9m8wnnwdufq3gk722tn8wa0lsxlwzfjjqynxgu0dehecyqdsk33nle`

Feel free to use the Sign Message feature from the Utils dApp and paste the signature in a comment: https://utils.multiversx.com/

Thanks.

**Comment by Toderean** [comment]
{
  "address": "erd1cdxt9m8wnnwdufq3gk722tn8wa0lsxlwzfjjqynxgu0dehecyqdsk33nle",
  "message": "0x39646435373135616539613539353834333730326432653165626366653232636561363638643861",
  "signature": "0xaad396e5abcba51d753ef2ddb5a8588bbe07a37aba080b8ea3d4616fc94c46bd4ee6dc458e093acc098642f1c40b52a7e7744ce302f657b570814f8a82703d0c",
  "version": 1,
  "signer": "ErdJS"
}

**Comment by paulmultiversx** [comment]
@Toderean 

Your branch is behind our master. Please make sure you have all our updates in your forked repository so we can approve & merge the PR. 

Thanks.

**Comment by Toderean** [comment]
{
  "address": "erd1cdxt9m8wnnwdufq3gk722tn8wa0lsxlwzfjjqynxgu0dehecyqdsk33nle",
  "message": "0x38333932373937353934626533626666383665643536396564393631346438353835376665393663",
  "signature": "0xffddbf28a82deba8a2b244309ab7bf42db5e213e51fed7e1bcab8d69ccd601c5bea70e5bc0678dbc301d2b1e342484f75f1bb70c1695723418f7dc51dc26aa0a",
  "version": 1,
  "signer": "ErdJS"
}

**Pull request merged**
